### ISSUE TITLE
logs for kubeadm cloud-init module

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#10]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Have a failed kubeadm join on a node

**What did you expect to happen:**
Expect to see kubeadm output in `/var/log/cloud-init-output.log`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The module doesn't capture output at the moment - should stream results out, redacting anything sensitive.

**Environment:**

- Cluster-api-provider-aws version: capa-ami-ubuntu-18.04-1.15.1-00-1563545503
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by detiber** [comment]
I think this could be closed since we are no longer using the custom kubeadm module.

**Comment by randomvariable** [comment]
This module was removed, so can

/close
