### ISSUE TITLE
Ensure FLATCAR_VERSION is available in Azure

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/image-builder#1002]
The release of Flatcar images published to Azure is sometimes delayed, which creates a situation, where `hack/image-grok-latest-flatcar-version.sh` and `az vm image list --publisher kinvolk --sku stable --offer flatcar-container-linux-free --all -o json | jq -r '.[] | select( .sku == "stable") | .version' | sort | tail -n1` will return different versions, which makes CI fail for Flatcar until latest image is published.

Perhaps we should change `hack/image-grok-latest-flatcar-version.sh` to use the latter command in case we deploy to Azure.

CC @dongsupark @jepio

**Comment by mboersma** [comment]
@invidian this happened again today:

```
[1;32m==> sig-flatcar: Resource group has been deleted.[0m
[1;31mBuild 'sig-flatcar' errored after 25 seconds 321 milliseconds: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplateDeployment" Message="The template deployment 'pkrdpxrmpb7i1qc' is not valid according to the validation procedure. The tracking id is 'fb87a505-7c4e-4547-9c3b-abd8fe55e4f0'. See inner errors for details." Details=[{"code":"InvalidParameter","message":"The following list of images referenced from the deployment template are not found: Publisher: kinvolk, Offer: flatcar-container-linux-free, Sku: stable, Version: 3374.2.0. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images.","target":"imageReference"}]
```

**Comment by mboersma** [comment]
It's still erroring today, btw, which is blocking some PRs from passing. 😞
