### ISSUE TITLE
Flatcar images built by image-builder does not support key auth in Openstack provider

### ISSUE THREAD

**Issue by okozachenko1203** [kubernetes-sigs/image-builder#1018]
**What steps did you take and what happened:**
- I built a qcow2 image by following https://image-builder.sigs.k8s.io/capi/providers/openstack.html#building-qcow2-image to build flatcar image for Openstack.
```bash
$ make build-qemu-flatcar
```
- Uploaded it to glance
- Spin up a VM using that image
```bash
$ openstack server create flatcar --image flatcar-3374.2.0-v1.25.3  --flavor v3-starter-2  --network public --key-name okozachenko_git
```
- Trying to access via ssh and it requires password
```bash
$ ssh core@162.253.55.100
The authenticity of host '162.253.55.100 (162.253.55.100)' can't be established.
ECDSA key fingerprint is SHA256:5n95nOYl/1TDiDTiIgrM3g0h7y9y+/DP3M4lTvQgGK8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '162.253.55.100' (ECDSA) to the list of known hosts.
Password:
```
**What did you expect to happen:**
I expect key auth.

**Anything else you would like to add:**
If i use the vanilla flatcar image, key auth is working.

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)): [Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi)

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
```shell
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- image builder version: v0.1.13

/kind bug
/area

**Comment by mnaser** [comment]
@okozachenko1203 

https://github.com/kubernetes-sigs/image-builder/blob/03def50db05d589d409cbe9409912e1f6cdc51fe/v1/pkg/engines/packer/variables.go#L102
https://github.com/kubernetes-sigs/image-builder/blob/03def50db05d589d409cbe9409912e1f6cdc51fe/v1/pkg/engines/packer/variables.go#L105

I'm scared it might work but can you try logging in using username `builder` and password `builder` ?

**Comment by okozachenko1203** [comment]
> @okozachenko1203
> 
> https://github.com/kubernetes-sigs/image-builder/blob/03def50db05d589d409cbe9409912e1f6cdc51fe/v1/pkg/engines/packer/variables.go#L102
> 
> 
> https://github.com/kubernetes-sigs/image-builder/blob/03def50db05d589d409cbe9409912e1f6cdc51fe/v1/pkg/engines/packer/variables.go#L105
> 
> I'm scared it might work but can you try logging in using username `builder` and password `builder` ?

@mnaser it does not work

**Comment by okozachenko1203** [comment]
Following this [doc ](https://flatcar-linux.org/docs/latest/installing/cloud/openstack/), I generated ignition JSON file from https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/files/flatcar/clc/bootstrap.yaml for openstack provider.
```bash
cat bootstrap.yaml | docker run --rm -i ghcr.io/flatcar/ct:latest -platform openstack-metadata > ignition.json
```

The result ignition file is;
```json
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.3.0"
  },
  "networkd": {},
  "passwd": {
    "users": [
      {
        "groups": [
          "wheel",
          "sudo",
          "docker"
        ],
        "name": "builder",
        "passwordHash": "BUILDERPASSWORDHASH"
      }
    ]
  },
  "storage": {},
  "systemd": {
    "units": [
      {
        "dropins": [
          {
            "contents": "[Service]\nEnvironment=COREOS_METADATA_OPT_PROVIDER=--provider=openstack-metadata",
            "name": "20-clct-provider-override.conf"
          }
        ],
        "name": "coreos-metadata.service"
      },
      {
        "dropins": [
          {
            "contents": "[Service]\nEnvironment=COREOS_METADATA_OPT_PROVIDER=--provider=openstack-metadata",
            "name": "20-clct-provider-override.conf"
          }
        ],
        "enabled": true,
        "name": "coreos-metadata-sshkeys@.service"
      },
      {
        "enable": true,
        "name": "docker.service"
      },
      {
        "mask": true,
        "name": "update-engine.service"
      },
      {
        "mask": true,
        "name": "locksmithd.service"
      }
    ]
  }
}
```

To recap, `coreos-metadata-sshkeys@.service` should be running.
