### ISSUE TITLE
make docker-build giving issue - invalid reference format

### ISSUE THREAD

**Issue by shruthihub** [kubernetes-sigs/image-builder#1047]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
on git clone and in images/capi directory , i ran make docker-build
but i got a error that says :
invalid argument "gcr.io//cluster-node-image-builder-amd64:dev" for "-t, --tag" flag: invalid reference format

**What did you expect to happen:**
docker image creation has to happen

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by mohitsharma-in** [comment]
Seems to be like you might not be able to run `REGISTRY ?= gcr.io/$(shell gcloud config get-value project)
` specifically shell gcloud section which might be resulting in the error.

Can you please try Passing REGISTRY=<path> make docker-build

**Comment by AverageMarcus** [comment]
Sorry for the delay, I've opened a PR to fix this so you don't need to override the registry if not needed: https://github.com/kubernetes-sigs/image-builder/pull/1199
