### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by Jonitich** [kubernetes-sigs/image-builder#1065]
Hi, 
I am getting this error while building the qemu VM for building an openstack image from ubuntu 20.04 
```
 qemu: TASK [containerd : download containerd] ****************************************
    qemu: fatal: [default]: FAILED! => {"changed": false, "dest": "/tmp/containerd.tar.gz", "elapsed": 0, "msg": "Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)>", "url": "https://github.com/containerd/containerd/releases/download/v1.6.15/cri-containerd-cni-1.6.15-linux-amd64.tar.gz"}
```
How can I pass custom certificates to avoid this error?
Thanks!

**Comment by invidian** [comment]
Can you try again? That seem like a transient error from GitHub.

**Comment by acr-varonis** [comment]
Adding Custom CAs to an image is very important in enterprise environments where the firewall does deep SSL inspection.

I would also love to know how to do something like this

**Comment by invidian** [comment]
I'm pretty sure custom CAs can be injected via instance custom data, via cloud-init or Ignition. I'm not sure if it make sense to support this on image-builder level.

**Comment by jsturtevant** [comment]
Agreed this would be done at cloud-init or ignition.  If there are other components that are outside the scope of the project it is possible use custom ansible roles as well: https://image-builder.sigs.k8s.io/capi/capi.html#enabling-ansible-custom-roles

closing as original issue was transient
/close
