### ISSUE TITLE
Support Mariner Linux as CAPI image base

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1070]
**Describe the solution you'd like**

Azure images should support Mariner Linux as a base.
https://github.com/microsoft/CBL-Mariner

**Describe alternatives you've considered**

**Additional context**

See also kubernetes-sigs/image-builder#1071

/kind feature

**Comment by mboersma** [comment]
cc: @BDworak

**Comment by CecileRobertMichon** [comment]
/close 

I just transferred the original issue
