### ISSUE TITLE
Support Mariner Linux as capi image base

### ISSUE THREAD

**Issue by BDworak** [kubernetes-sigs/image-builder#1071]
/kind feature

**Describe the solution you'd like**
We are being asked to move our linux base images to mariner linux. https://github.com/microsoft/CBL-Mariner
This ask is to create the Mariner Linux image to be used as the base image for both the controller and worker nodes in a Kubernetes CAPZ cluster. Ideally, this base image is built as part of the CAPI image building infrastructure and is published for use in Azure natively, similar to existing images. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: N/A
- Kubernetes version: (use `kubectl version`): 1.24.1+ 
- OS (e.g. from `/etc/os-release`): N/A

**Comment by CecileRobertMichon** [comment]
Note that we may need to do something like https://github.com/Azure/AgentBaker/pull/2799 as part of this. 

> This config also explicitly sets LimitNOFILE=1048576. This is because LimitNOFILE=infinity on Mariner means 1073741816, which has caused issues running some software in containers such as mysql5 and sshd. The value 1048576 matches the behavior on the Ubuntu AKS host.
