### ISSUE TITLE
Ubuntu 22.04.1 ISO not found

### ISSUE THREAD

**Issue by raykrueger** [kubernetes-sigs/image-builder#1083]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
While executing `make build-node-ova-vsphere-ubuntu-2204` (or any ubuntu 22.04 ova build) I received the following error output:
```
vsphere: output will be in this color.

==> vsphere: Retrieving ISO
==> vsphere: Trying https://releases.ubuntu.com/22.04/ubuntu-22.04.1-live-server-amd64.iso
==> vsphere: Trying https://releases.ubuntu.com/22.04/ubuntu-22.04.1-live-server-amd64.iso?checksum=sha256%3A10f19c5b2b8d6db711582e0e27f5116296c34fe4b313ba45f9b201a5007056cb
==> vsphere: Download failed bad response code: 404
==> vsphere: error downloading ISO: [bad response code: 404]
Build 'vsphere' errored after 772 milliseconds 245 microseconds: error downloading ISO: [bad response code: 404]
```

**What did you expect to happen:**
I expected the Ubuntu 22.04 ISO to download successfully

**Anything else you would like to add:**
After a little poking around it seems the 22.04.1 live iso was replaced with a 22.04.2 ISO.
https://releases.ubuntu.com/jammy/

After replacing the ISO with https://releases.ubuntu.com/jammy/ubuntu-22.04.2-live-server-amd64.iso and the shasum from https://releases.ubuntu.com/jammy/SHA256SUMS in packer/ova/ubuntu-2204.json it gets past this point.

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version: v1.8.5
- Packer Provider: vsphere
- Ansible Version: 2.9.6
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by raykrueger** [comment]
I should add that I’m happy to submit the PR for this.

**Comment by kkeshavamurthy** [comment]
Thanks @raykrueger . Feel free to open up a PR. 
Looks like the older ISOs are moved to https://old-releases.ubuntu.com/releases/jammy/

**Comment by raykrueger** [comment]
I believe the ansible process does a dist upgrade on the ISO anyway, is that correct?

If so, would it make sense to point to the 22.04.1 in old releases? Otherwise we'll be coming back with a new PR for every point release. However, the new ISO would shorten that patching process some.

**Comment by kkeshavamurthy** [comment]
Yup, correct. 
Pointing to the (latest-1) ISO in old-releases makes sense since the links will not break.

**Comment by raykrueger** [comment]
PR is up. One nice thing about switching to the old-releases location is that I don't have to change the sha256 values at all :)
