### ISSUE TITLE
Audit CAPA and wardroom

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/image-builder#11]
In an effort to dedupe and reduce the number of tools being used in the ecosystem, we should do a final audit of CAPA's image builder and https://github.com/heptiolabs/wardroom as well. 

/assign @codenrhoden @figo

**Comment by codenrhoden** [comment]
@detiber With https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/993 merged, do you feel like an audit of Wardroom is still needed? I have the cycles now to look through that if so.

**Comment by detiber** [comment]
@codenrhoden yes, I found a few additional changes that we should likely make:
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/773690f16e3a783871cc1008c043f1352f9dd10e#diff-2607486c24fcfe5e058547dd451c4466
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/61b5feb31a94c60de352117a491f8adb62dad4b9#diff-2607486c24fcfe5e058547dd451c4466
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/963/files

**Comment by codenrhoden** [comment]
@detiber Good news -- the code to handle private/encrypted AMIs is already there. That was all Packer related changes, and those were all picked up by the import of the Packer related stuff from CAPA that was made 20 days ago. So nothing was missed there.

I'm scanning back now to see if there were other changes to the Ansible roles that could have been missed, as those were imported from CAPV, not CAPA, and CAPV split off from CAPA earlier on, so any changes there could have been missed. So far the one you highlighted (resulting in https://github.com/kubernetes-sigs/image-builder/pull/28) is the only one I've seen, but I'll keep looking.

**Comment by codenrhoden** [comment]
so I'm not super familiar with wardroom, but I looked through it's ansible roles as well. The only thing that stands out in there to me is https://github.com/heptiolabs/wardroom/pull/142. I'm guessing this is functionality that is now handled by kubeadm, but I don't really know. Any idea if something similar belongs here as well?

/cc @detiber

**Comment by detiber** [comment]
@codenrhoden that is correct, we don't need to muck with the systemd environment for the kubelet since kubeadm exposes configuration for it.

**Comment by codenrhoden** [comment]
Awesome. I consider this complete, then.
/close
