### ISSUE TITLE
Add building images for Hetzner

### ISSUE THREAD

**Issue by simonostendorf** [kubernetes-sigs/image-builder#1123]
**Is your feature request related to a problem? Please describe.**
I want to use image builder to build flatcar image for CAPI on Hetzner Cloud

**Describe the solution you'd like**
Build Hetzner snapshot with flatcar as OS and all CAPI prerequisites installed. 

Or generate a ignition file that can be applied by own packer script to hetzner servers that installs all capi prerequisites. 

**Describe alternatives you've considered**
Manually create hetzner server to later create a snapshot (e.g. using packer or manual commands) to create flatcar image. After that i don't know to get the needed ignition file to install all CAPI files. If you help me to find these maybe the workaround is enough. 

/kind feature

**Comment by AverageMarcus** [comment]
Hi @simonostendorf, as Hertzner isn't an official CAPI provider (as stated in their [README](https://github.com/syself/cluster-api-provider-hetzner/tree/main#readme)) we're unlikely to see effort spent on this unless [Syself](https://github.com/syself) decide to contribute to `image-builder`. If this is a priority for you then you might want to reach out to them / the [cluster-api-provider-hetzner](https://github.com/syself/cluster-api-provider-hetzner/) project to see if they can help add support to `image-builder`.

**Comment by AverageMarcus** [comment]
That would be great if you're able to! We'll help where we can if needed. Feel free to reach out to folks in the [#image-builder](https://kubernetes.slack.com/archives/C01E0Q35A8J) slack channel if needed. 😄

**Comment by cornelius-keller** [comment]
@simonostendorf @AverageMarcus  I have created a [PR for building images for hetzner ](https://github.com/kubernetes-sigs/image-builder/pull/1170). @simonostendorf it also builds an image for flatcar.

**Comment by simonostendorf** [comment]
> @simonostendorf @AverageMarcus  I have created a [PR for building images for hetzner ](https://github.com/kubernetes-sigs/image-builder/pull/1170). @simonostendorf it also builds an image for flatcar. 

Amazing, I would love to use the image builder soon for Hetzner images and especially for flatcar. Thanks for your work. Unfortunately I haven't found the time to create it myself, even though I wrote it above.

**Comment by simonostendorf** [comment]
Implemented by https://github.com/kubernetes-sigs/image-builder/pull/1170
