### ISSUE TITLE
QEMU build of Ubuntu 22.04 installs a package related to VMWare

### ISSUE THREAD

**Issue by mikejoh** [kubernetes-sigs/image-builder#1131]
**What steps did you take and what happened:**
I noticed that during a `qemu` build of Ubuntu 22.04 running the following command:
```
make build-qemu-ubuntu-2204
```
within `images/capi` directory we're installing `open-vm-tools` as an additional package here:

https://github.com/kubernetes-sigs/image-builder/blob/2e96edbc8edcfde228860c2b9dff55342b851ee1/images/capi/packer/ova/linux/ubuntu/http/22.04/user-data#L62-L63

https://github.com/kubernetes-sigs/image-builder/blob/2e96edbc8edcfde228860c2b9dff55342b851ee1/images/capi/packer/ova/linux/ubuntu/http/22.04.efi/user-data#L83-L84

The PR that added those files (#1003) mentions adding support for VMWare and `open-vm-tools` is specific to VMWare. I guess the problem stems from the fact that the `linux` file [here](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/qemu/linux) is a symlink to `../ova/linux`? It feels like we need to split things up a bit or copy-paste basically, if possible.

**What did you expect to happen:**
Not to have a VMWare specific tool installed as part of the Ubuntu autoinstaller by default.

**Anything else you would like to add:**
N/A

**Environment:**
N/A

**Comment by sriramandev** [comment]
Guess then the issue should also be present in the previous versions as well... older version have similar preseed happening [here](https://github.com/kubernetes-sigs/image-builder/blob/3c9c5642ac78be02ff631a19fef6fc3dab4c1a90/images/capi/packer/ova/linux/ubuntu/http/base/preseed.cfg#L102)

**Comment by AverageMarcus** [comment]
/remove-lifecycle stale

I have an open PR for this issue. I'll try and get it reviewed.
