### ISSUE TITLE
[support] Till what kubernetes version it is supported presently till tag v0.1.14

### ISSUE THREAD

**Issue by ATP-55** [kubernetes-sigs/image-builder#1140]
As of tag v0.1.14, what is the latest Kubernetes version that is supported? 

can i use it for k8s 1.27?

**Comment by mboersma** [comment]
@ATP-55 I think there was an issue (#1130) that prevented Kubernetes v1.127 images from building. This should be fixed in the new image-builder v0.1.15 release: https://github.com/kubernetes-sigs/image-builder/releases/tag/v0.1.15

**Comment by mboersma** [comment]
/close

@ATP-55 please let us know if you see any issues using Kubernetes 1.27 with current image-builder. We've been building CAPZ reference images and haven't seen problems.
