### ISSUE TITLE
ova image ubuntu 22.04 udev net rule ens* eth* ip address not released

### ISSUE THREAD

**Issue by dscaravaggi** [kubernetes-sigs/image-builder#1153]
**What happened:**
Image stuck after initial control plane waiting for become available

**What did you expect to happen:**
Image ready and worker nodes too

**work around**
change network assignment rule from ens* to e*
adopting regex e*  any  eth* and ens* are covered as well 

**Environment:**
 latest

**Note:**
I noticed that udev network rule for naming networks should be **ens*** 

/kind bug

**Comment by dscaravaggi** [comment]
file chnged is  /images/capi/cloudinit/meta-data

give a look to the file where rules.d id deleted :

https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/ova/linux/ubuntu/http/base/preseed.cfg

and this one: 

https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/sysprep/files/etc/netplan/51-kubevirt-netplan.yaml

**Comment by dscaravaggi** [comment]
I'm not able to detect the exact cloud init step wich turn ens192 back to eth0

dmesg | grep -i eth

```
[    5.206207] vmxnet3 0000:0b:00.0 eth0: NIC Link is Up 10000 Mbps
[    5.521328] vmxnet3 0000:0b:00.0 ens192: renamed from eth0
[   13.945937] vmxnet3 0000:0b:00.0 eth0: renamed from ens192
[   16.957958] vmxnet3 0000:0b:00.0 eth0: intr type 3, mode 0, 3 vectors allocated
[   16.959089] vmxnet3 0000:0b:00.0 eth0: NIC Link is Up 10000 Mbps
[  187.312525] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready

```

**Comment by AverageMarcus** [comment]
@dscaravaggi Are you able to confirm if this is still an issue or not with the latest image-builder release?

**Comment by dscaravaggi** [comment]
> @dscaravaggi Are you able to confirm if this is still an issue or not with the latest image-builder release?

Honestly , I dismounted the LAB network
I switched to Tanzu TGK (2.4) 
In any case after an update to vcenter 7.0.3 I got an internal build errror before completing ova assembling , I will attach the exact error
