### ISSUE TITLE
Add all maintainers to k8s.io OWNERS

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1156]
In trying to sync up housekeeping files with current image-builder owners (see kubernetes/k8s.io#5263), I wasn't able to add @EleanorRigby or @kkeshavamurthy because they're not yet members of the kubernetes GitHub org.

Membership in kubernetes-sigs is transferable to kubernetes, so this should be just a matter of requesting membership. When that is granted, we can create PRs to grant appropriate owner access.

/kind feature
/assign @kkeshavamurthy @EleanorRigby

**Comment by mboersma** [comment]
/unassign @EleanorRigby 
see #1173.

**Comment by kkeshavamurthy** [comment]
Thanks @mboersma 
I've opened the [PR](https://github.com/kubernetes/org/pull/4263#issuecomment-1576002882)

**Comment by mboersma** [comment]
I closed this prematurely: see kubernetes/k8s.io#5369

**Comment by mboersma** [comment]
/close

This time for reals.
