### ISSUE TITLE
Ubuntu 22.04 image size

### ISSUE THREAD

**Issue by feitnomore** [kubernetes-sigs/image-builder#1169]
**Is your feature request related to a problem? Please describe.**
The images for Ubuntu 22.04 are almost 4 times bigger than Ubuntu 20.04:
```
4.1G	ubuntu-2004-kube-v1.25.10.qcow2
4.1G	ubuntu-2004-kube-v1.26.0.qcow2
16G	ubuntu-2204-kube-v1.25.10.qcow2
14G	ubuntu-2204-kube-v1.26.0.qcow2
```

**Describe the solution you'd like**
Is there anything that can be done to optimize the size of ubuntu 22.04 images?

**Describe alternatives you've considered**
Haven't considered anything. I wish there was those old netinst images to solve it.

/kind feature

**Comment by chess-knight** [comment]
Hello @feitnomore.
I experienced the same in #1155, where I successfully used `virt-sparsify` to shrink image size but that doesn't solve this problem, because it is additional post-processing.

**Comment by chess-knight** [comment]
Hello @feitnomore.
I created PR #1182 with a potential fix for this problem. Can you try that changes, if it works for you, please?

**Comment by feitnomore** [comment]
Looking a lot better over here 👍

**Comment by ffais** [comment]
@chess-knight it's working fine for me. The final image now is 4GB, compared to the previous one is a big improvement.

**Comment by chess-knight** [comment]
Thank you @feitnomore and @ffais for testing.
