### ISSUE TITLE
couldn't resolve module/action 'amazon.aws.s3_object'.

### ISSUE THREAD

**Issue by tuxtof** [kubernetes-sigs/image-builder#1185]
**What steps did you take and what happened:**

since commit https://github.com/kubernetes-sigs/image-builder/commit/5a255064687683ad7e2d9e9d6cb246747b0ee1dc

when we try to use load_additional_components it failed with the following error

`ERROR! couldn't resolve module/action 'amazon.aws.s3_object'. This often indicates a misspelling, missing collection, or incorrect module path.` 

even if we don't use additional_s3

what is expected here  ???

do we need to add hack/ensure_s3 to each target ?

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): linux ubuntu 2204
- Packer Version: 1.8.7
- Packer Provider: n/a
- Ansible Version: 2.11.5
- Cluster-api version (if using): n/a
- Kubernetes version: (use `kubectl version`): n/a

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by drew-viles** [comment]
/assign @drew-viles 

I've got a fix being tested for this now.
