### ISSUE TITLE
gcp-all-nightly testgrid job continually failing

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1190]
**What steps did you take and what happened:**

This job has been failing every night for a while:
https://testgrid.k8s.io/sig-cluster-lifecycle-image-builder#periodic-image-builder-gcp-all-nightly

**What did you expect to happen:**

We should fix this or disable it if it's no longer informative.

/kind failing-test

**Comment by mboersma** [comment]
This may be closed by #1200: see [this job](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-image-builder-gcp-all-nightly/1671179816591691776) in progress. High five to @AverageMarcus.

**Comment by mboersma** [comment]
That issue was indeed fixed, but a new one is now failing the job:

```
[0;32m    googlecompute.rhel-8: TASK [setup : add epel repo] ***************************************************[0m
[0;32m    googlecompute.rhel-8: changed: [default][0m
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:164","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2023-06-20T17:35:06Z"}
```

I can make a PR to extend the timeout, and/or we could skip testing Kubernetes 1.24 now I think. cc: @cpanato.

**Comment by cpanato** [comment]
i will take care
/assign

**Comment by cpanato** [comment]
looks like now it is building more images, like rhel-8
I will extend the timeout to give more time to build everything
