### ISSUE TITLE
Update CNI plugins to v.1.3.0

### ISSUE THREAD

**Issue by hrak** [kubernetes-sigs/image-builder#1196]
**Is your feature request related to a problem? Please describe.**

CNI plugins 1.3.0 [is released](https://github.com/containernetworking/plugins/releases/tag/v1.3.0) but does not appear yet on the location that image-builder uses.

Update CNI plugins to 1.3.0 once they appear at https://storage.googleapis.com/k8s-artifacts-cni/

**Describe the solution you'd like**

This issue is mostly a reminder to check https://storage.googleapis.com/k8s-artifacts-cni/ every now and then

**Describe alternatives you've considered**

**Additional context**

/kind feature

**Comment by mboersma** [comment]
Still not published to that location; v1.2.0 is the latest there.

**Comment by mboersma** [comment]
Wow, they finally got published. I'll make a PR.

**Comment by kranurag7** [comment]
@mboersma I would like to give this a try. On main, we are still using 1.2.0 semver. 

https://github.com/kubernetes-sigs/image-builder/blob/7cb76c78e013db59783b93815caf710c5ad34bef/images/capi/packer/config/cni.json#L2-L7

**Comment by mboersma** [comment]
@kranurag7 please do--feel free to `/assign` yourself--and thanks!

I tried to update these fields naively a while back but hit this failure:

```shell
    azure-arm.sig-ubuntu-2204: TASK [kubernetes : Install Kubernetes] *****************************************
    azure-arm.sig-ubuntu-2204: fatal: [default]: FAILED! => {"cache_update_time": 1698940472, "cache_updated": false, "changed": false, "msg": "no available installation candidate for kubernetes-cni=1.3.0-1.1"}
```

Hopefully you have better luck.
