### ISSUE TITLE
Ability to build Photon OS 5 OVA images

### ISSUE THREAD

**Issue by DimpleRajaVamsi** [kubernetes-sigs/image-builder#1214]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to build Photon OS 5 OVA images

**Describe alternatives you've considered**
NA

**Additional context**
- https://github.com/vmware/photon/wiki/What-is-New-in-Photon-OS-5.0
- https://github.com/vmware/photon/releases/tag/5.0-GA

/kind feature

**Comment by lgayatri** [comment]
@kkeshavamurthy , can this request be prioritised please?

**Comment by AverageMarcus** [comment]
@lgayatri @DimpleRajaVamsi are either of you willing to work on this? 

`image-builder` is run by volunteers and relies on contributions from others to support new providers and OS versions. If you're not able to you might want to reach out to the [cluster-api-provider-vsphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere) project (ideally on Slack) to see if anyone there is working on adding support to `image-builder`.

**Comment by lgayatri** [comment]
Ack @AverageMarcus.
