### ISSUE TITLE
Add support for cdrom_type and http_ip packer variables

### ISSUE THREAD

**Issue by jvrahav** [kubernetes-sigs/image-builder#1228]
**Is your feature request related to a problem? Please describe.**
cdrom_type
ide device is deprecated in the latest linux kernel as of linux 5.2. currently image builder defaults cdrom to ide for ova builder. the latest kernels require cd rom device to be backed by SATA.
packer exposes cdrom_type variable to configure the device. However this cannot be used with image builder as builder is not aware of this variable

http_ip
When using image-builder on multi-nic setups we are unable to configure with packer to indicate which interface packer has to pick.
packer exposes http_ip variable which can be used to configure packer to bind to a specific interface

**Describe the solution you'd like**
expose cdrom_type and http_ip packer variables as node config for ova

**Describe alternatives you've considered**
attempts to set the packer variables failed as the variables were not passed on to packer

/kind feature

**Comment by kkeshavamurthy** [comment]
Fixed in https://github.com/kubernetes-sigs/image-builder/pull/1229
