### ISSUE TITLE
Remove EoL OSs from providers

### ISSUE THREAD

**Issue by AverageMarcus** [kubernetes-sigs/image-builder#1232]
We've got a lot of OSs still included as defaults in our providers that have passed their end of life for support now. I think we should remove these from the project (people that rely on them can always supply their own packer values if needed or use an older version).

End of life OSs that I've seen:

* Ubuntu 18.04 - #1264
* Windows 2004 - #1271

**Comment by mboersma** [comment]
CentOS 7 [is supported](https://www.redhat.com/en/topics/linux/centos-linux-eol) until June 30, 2024, but CentOS 8 reached [end-of-life](https://www.centos.org/centos-linux-eol/) on December 31, 2021.

We should remove CentOS 8, but its only usage in image-builder that I see is with the IBM Cloud PowerVS support. That's actually the only distro that provider supports, so removing it really implies removing the whole provider. Maybe we should give them a chance to update it before we suggest removing everything.

**Comment by AverageMarcus** [comment]
Yeah, if it turns out that no one is actually using IBM Cloud PowerVS then removing the whole provider is even better. One less things to maintain.

**Comment by mboersma** [comment]
@mkumatag we have a question for you, as the author of PowerVS support in #860.

We're trying to clean up unsupported Linux distros from the image-builder project, and CentOS 8 is one of those (see above). Do you think it's reasonable to update the `powervs` provider to a supported distro, or should we remove it?

**Comment by mkumatag** [comment]
We are using [centos stream 8](https://www.centos.org/centos-stream/) which is still supported OS and no need to remove it.

**Comment by AverageMarcus** [comment]
Oh! We’re mixing up CentOS Linux and CentOS Stream. 🤦
Did that mean we don’t have any CentOS to remove?

**Comment by AverageMarcus** [comment]
@mboersma i think we’re good to close this now. Do you agree?

**Comment by mboersma** [comment]
@AverageMarcus agreed. Thanks for the clarification @mkumatag!
