### ISSUE TITLE
Add Support for creating Proxmox VM templates.

### ISSUE THREAD

**Issue by mcbenjemaa** [kubernetes-sigs/image-builder#1257]
**Is your feature request related to a problem? Please describe.**

We are using Proxmox to provision vanilla Kubernetes clusters.
and we also implementing a capi provider.

Although, we can use qemu provider to build images
But, I think automating the creation of proxmox templates is a way better.

**Describe the solution you'd like**
Having a Proxmox target that enables to create VM, boot from ISO, install stuff. and then stop it, and convert it to template.

**Describe alternatives you've considered**

 packer proxmox builders can be used: https://developer.hashicorp.com/packer/plugins/builders/proxmox

build images manually with qemu.

**Additional context**
This can be achived via communicating with Proxmox API.

/kind feature

**Comment by olinux-dev** [comment]
looks interesting, would like to take that over. And if someone wants to join let me know

**Comment by mcbenjemaa** [comment]
Yeah, I will try to look into this once I have time.
