### ISSUE TITLE
Can not apply static ip to photon vm by clusterapi

### ISSUE THREAD

**Issue by luniHw** [kubernetes-sigs/image-builder#126]
Environment as below:
1. capv is v0.5.3
2. clusterapi is v0.2.9

Question is that can not apply static ip to photon.
the log recorded in /var/log/cloud-init-output.log shows as below
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/21055782/72577098-78f60000-390c-11ea-8a0d-cc445e45a15b.png">

**Comment by figo** [comment]
Please file the issue under https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/
Thanks

**Comment by figo** [comment]
refer from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/756
this been fixed with capv 0.5.5, will close it right now.

/close
