### ISSUE TITLE
[ova] Add support for vApp properties when using vsphere-clone

### ISSUE THREAD

**Issue by fad3t** [kubernetes-sigs/image-builder#1263]
I'm using image-builder to build Ubuntu 22.04 images on vSphere.
I'm using the daily cloud image from Ubuntu, which requires user-data to be bootstrapped.
It is possible to pass the user-data to the VM using the vApp properties, however the current Packer template doesn't support it.

It does look like this:
```json
       "vapp": {
         "properties": {
           "user-data": "{{user `user_data`}}"
         }
       },
```
`user_data` being the b64-encoded user data config.

I'll submit a PR to include it, however I'm wondering if this could have side-effects on images built from the Ubuntu live server ISO file..

If somebody has another idea, it's more than welcome. Note I cannot use any kind of HTTP bootstrap as the image is being built in a CI environment.

Thanks.

/kind feature

**Comment by fad3t** [comment]
Any thoughts?

**Comment by AverageMarcus** [comment]
@fad3t I suggest asking in the [image-builder Slack channel](https://kubernetes.slack.com/messages/image-builder) as you're likely to get better discussion there. 

From my perspective it sounds ok but I don't know enough about vSphere to know if there will be any side-effects or not.
