### ISSUE TITLE
Ansible bump to 2.15.3 causing issue with ensure-ansible.sh

### ISSUE THREAD

**Issue by tuxtof** [kubernetes-sigs/image-builder#1281]
**What steps did you take and what happened:**

if ansible is not installed and python is v3.8 (like in ubuntu 2004 LTS)
PR #1275 is causing issue when ensure-ansible.sh try to install ansible

ensure-ansible.sh failed with

```
hack/ensure-ansible.sh
fatal: No names found, cannot describe anything.
ERROR: Could not find a version that satisfies the requirement ansible-core==2.15.3 (from versions: 0.0.1a1, 2.11.0b1, 2.11.0b2, 2.11.0b3, 2.11.0b4, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1rc1, 2.11.1, 2.11.2rc1, 2.11.2, 2.11.3rc1, 2.11.3, 2.11.4rc1, 2.11.4, 2.11.5rc1, 2.11.5, 2.11.6rc1, 2.11.6, 2.11.7rc1, 2.11.7, 2.11.8rc1, 2.11.8, 2.11.9rc1, 2.11.9, 2.11.10rc1, 2.11.10, 2.11.11rc1, 2.11.11, 2.11.12rc1, 2.11.12, 2.12.0b1, 2.12.0b2, 2.12.0rc1, 2.12.0, 2.12.1rc1, 2.12.1, 2.12.2rc1, 2.12.2, 2.12.3rc1, 2.12.3, 2.12.4rc1, 2.12.4, 2.12.5rc1, 2.12.5, 2.12.6rc1, 2.12.6, 2.12.7rc1, 2.12.7, 2.12.8rc1, 2.12.8, 2.12.9rc1, 2.12.9, 2.12.10rc1, 2.12.10, 2.13.0b0, 2.13.0b1, 2.13.0rc1, 2.13.0, 2.13.1rc1, 2.13.1, 2.13.2rc1, 2.13.2, 2.13.3rc1, 2.13.3, 2.13.4rc1, 2.13.4, 2.13.5rc1, 2.13.5, 2.13.6rc1, 2.13.6, 2.13.7rc1, 2.13.7, 2.13.8rc1, 2.13.8, 2.13.9rc1, 2.13.9, 2.13.10rc1, 2.13.10, 2.13.11rc1, 2.13.11)
ERROR: No matching distribution found for ansible-core==2.15.3
make: *** [Makefile:174: deps-all] Error 1
```

trying to reproduce manually we see that there is another error who explain the problem

```
ERROR: Ignored the following versions that require a different python version:  2.15.3 Requires-Python >=3.9; 
```

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by mboersma** [comment]
@tuxtof yes that change did require Python 3.9 or greater, we updated the Docker image to 22.04 to cover that but weren't apparently thinking of build pipelines. Let's revert that change.

**Comment by tuxtof** [comment]
yes same on my side update on build image fix the issue, maybe we can just add an additional test inside the script to test python and failed properly

**Comment by jsturtevant** [comment]
We discussed at office hours this morning, and suggest using the latest release https://github.com/kubernetes-sigs/image-builder/releases and we will work on solving this problem for the next release.  

@tuxtof does that work as a way to unblock you?

**Comment by AverageMarcus** [comment]
To add on to what James said...

I think it would be best to introduce a script to perform the Python version check before we make the next tagged release

**Comment by tuxtof** [comment]
@jsturtevant not blocked on my side we have updated our build image to 22.04 so no more issue :-D
