### ISSUE TITLE
All ansible actions should use fully-qualified collection name

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1312]
**What steps did you take and what happened:**

Run `make -C images/capi lint` and see that there are numerous warnings from `ansible-lint` that the project is ignoring.

In particular, there are many "FQCN" warnings. It's safer and generally preferable to use the full name of ansible actions–that is, `community.windows.win_firewall_rule` instead of just `win_firewall_rule`, for example.

**What did you expect to happen:**

Running `make -C images/capi lint` shouldn't result in any `fqcn[action]` warnings.

**Anything else you would like to add:**

One way to accomplish this:

```shell
ansible-lint --fix=fqcn images/capi/ansible
make -C images/capi lint-ignore
git add images/capi
git commit -m "Ansible actions use fully-qualified collection names"
```

These commands:
- Tell the linter to fix this `fqcn` type of warning automatically
- Regenerate the `.ansible-lint-ignore` file so these warnings won't be ignored in the future
- Add all the changed files to version control and commit them.

Then run `make -C images/capi lint` to ensure it's passing, and create a PR.

**Environment:**

N/A

/kind bug
/help
/good-first-issue

**Comment by mboersma** [comment]
Let's try to fix #1313 first, since fixing this will also include those changes and it would be saner to review separately.

**Comment by khannakshat7** [comment]
Hey @mboersma, I would like to work on this once #1313 is fixed.
/assign

**Comment by pranavp2005** [comment]
I am new to contributing to opensource. I would like to take this up as my first issue.
/assign

**Comment by mboersma** [comment]
@pranavp2005 I think @khannakshat7 claimed this one first, just fyi.

I think we should wait for #1338 to merge before making this change. Otherwise `ansible-lint --fix=fqcn` will include several unrelated formatting changes.

**Comment by pranavp2005** [comment]
> @pranavp2005 I think @khannakshat7 claimed this one first, just fyi.
> 
> I think we should wait for #1338 to merge before making this change. Otherwise `ansible-lint --fix=fqcn` will include several unrelated formatting changes.

Okay, thank you for informing me.

**Comment by mboersma** [comment]
@pranavp2005 we haven't heard anything from @khannakshat7 so if you're still available to take this on, please do. Sorry to slow things down.

**Comment by mboersma** [comment]
Here are updated commands that should help to create this PR:

```console
cd images/capi
rm .ansible-lint-ignore
ansible-lint --fix=fqcn ansible
make lint-ignore
git add .
git commit -m "Ansible actions use fully-qualified collection names"
```

**Comment by jongwooo** [comment]
Can I work on this issue?
