### ISSUE TITLE
`make lint` should also check shell scripts

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1327]
**Is your feature request related to a problem? Please describe.**

There are quite a few (bash) shell scripts in image-builder. Currently the `make lint` target only covers ansible files, but it could be expanded to cover shell scripts.

**Describe the solution you'd like**

`make lint` runs [`shellcheck`](https://www.shellcheck.net/) over .sh files and reports any errors or warnings it finds.

This probably requires writing an `ensure-shellcheck.sh` script to install the binary (although there is also a Docker container which may be easier to use) and also fixing whatever errors the linter initially reports. This could be a fair amount of work, although probably not too difficult overall.

**Describe alternatives you've considered**

**Additional context**

/kind feature

**Comment by mboersma** [comment]
@NotAName320 any progress? Let us know if you need any help, just ask here or [on Slack](https://kubernetes.slack.com/archives/C01E0Q35A8J). And thanks for helping out Kubernetes!

If you don't think you'll get to this soon, please `/unassign` so it's available for others.

**Comment by NotAName320** [comment]
@mboersma sorry, I've been working on this in the background but I've also been balancing schoolwork. Will get something in the next week or so.
