### ISSUE TITLE
Build base images from community CIS Benchmark Images

### ISSUE THREAD

**Issue by itmecho** [kubernetes-sigs/image-builder#133]
To comply with certain compliance controls, the CIS benchmarks are required. It would be great if the kops AMIs were built from the community CIS Debian images. This would give a certain level of free system hardening out of the box.  

For example:
CIS Debian Linux 9 Benchmark v1.0.0.5 - Level 1: `ami-003c5a72f53c93f63`

**Comment by detiber** [comment]
This might also be something interesting to look at for the base images in the capi image builder as well, the full list of available aws images from CIS is here: https://www.cisecurity.org/cis-hardened-images/amazon/

**Comment by randomvariable** [comment]
There's some interesting things about mounts in the CSI Benchmarks. Will need to check, but for example, I believe `/opt` is one of the read-only mounts, and that will potentially block CNI from working (I've always wished we used `/usr/libexec/cni` for them, but anyway).

In any case, a fair amount of validation work to be done.

**Comment by bagnaram** [comment]
To further this request, would be to break out volumes into separate STIG partitions. Other breaking hardening steps that come to mind would be mounting `/tmp` with noexecute bit set. These are some hardening steps that break kubernetes under certain circumstances that require maintaing a list of POAM, or mitigation steps
