### ISSUE TITLE
Don't install azure client by default

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1330]
**What steps did you take and what happened:**

When building images for Azure (that is, running `make build-azure-<foo>`), the `az` command-line client is installed on each Linux (and soon, Windows) image.

**What did you expect to happen:**

The `az` client is convenient for development and troubleshooting, but isn't appropriate for production images. This should be an option that must be turned on explicitly.

**Anything else you would like to add:**

See also #1326

/kind bug

**Comment by AverageMarcus** [comment]
The `az` client will be needed if uploading the images to an image gallery wont it? 
Isn't it needed to perform an `az login` prior to running the Make target? (At least that's what we've needed to do when using the container image)

**Comment by AverageMarcus** [comment]
Oh sorry, I was confusing including it in the Docker image with in the final VM image. Ignore me 😄
