### ISSUE TITLE
Flatcar Azure images are booting with broken /etc/resolv.conf

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/image-builder#1346]
I'm opening this issue for visibility and to discuss what mitigation we should provide to users.

As described in https://github.com/flatcar/Flatcar/issues/1265, image-builder Flatcar images with Flatcar version stable 3602.2.2 have currently broken DNS resolution when booted.

We could possibly mitigate it on image-builder level with the following patch:
```diff
diff --git images/capi/packer/azure/packer.json images/capi/packer/azure/packer.json
index a472e5950..553923f70 100644
--- images/capi/packer/azure/packer.json
+++ images/capi/packer/azure/packer.json
@@ -192,7 +192,7 @@
       ],
       "inline": [
         "if [[ $BUILD_NAME != \"flatcar\"* ]]; then exit 0; fi",
-        "sudo bash -c \"/usr/share/oem/python/bin/python /usr/share/oem/bin/waagent -force -deprovision+user && sync\""
+        "sudo bash -c \"/usr/share/oem/python/bin/python /usr/share/oem/bin/waagent -force -deprovision+user && ln -sf ../run/systemd/resolve/resolv.conf /etc/resolv.conf && sync\""
       ],
       "inline_shebang": "/bin/bash -x",
       "remote_folder": "{{user `provisioner_remote_folder`}}",
```

Right now [CAPZ e2e tests](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-main) are failing because of this. With this patch, we should be able to rebuild Azure images and fix tests without temporarily fixing Flatcar templates.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by invidian** [comment]
>Just to confirm, based on the linked issue this seems to be a problem with the waagent command removing the file, is that correct?
If so, this is limited to Azure I think as it's the only place it's used. 

Yes, right now the impact is limited to only Azure images.

>Do you know the purpose of this command? I'm not familiar with it.

As explained in Flatcar issue:
>With [image-builder](https://github.com/kubernetes-sigs/image-builder) project, as part of building Flatcar CAPI images, we run /usr/share/oem/bin/waagent -force -deprovision+user before shutting down building machine to ensure resulting OS image can be used for booting multiple instances.

**Comment by AverageMarcus** [comment]
> ensure resulting OS image can be used for booting multiple instances.

That's the bit I don't understand, sorry, I'm not that experienced with Azure. Why is this required for Azure and not other providers? (I just want to understand, not trying to block this 😄)

/cc @mboersma as you might be able to offer better insight from Azure perspective. 

/label area/provider/azure

**Comment by AverageMarcus** [comment]
@invidian Do you think we should keep this issue open to keep track until the upstream issue is resolved?
