### ISSUE TITLE
Can't build Kubernetes v1.29.0 image

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1363]
**What steps did you take and what happened:**

Trying to build an Ubuntu image for the new k8s v1.29.0 leads to an error finding the v1.2.0 version of the `kubernetes-cni` .deb package. It appears that verion v1.3.0 is now required alongside the v1.29.0 packaging (at least for Debian-ish distros).

But updating to use the v1.3.0 `kubernetes-cni` leads to problems building older versions of Kubernetes. This needs to be made conditional so image-builder can handle all supported versions of k8s.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version:
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by tuxtof** [comment]
maybe it time to implement independent settings by k8s release and have a var to select the k8s version ??

**Comment by berendt** [comment]
That‘s the failed task:

``` 
�[0;32m    qemu: TASK [kubernetes : Install Kubernetes] *****************************************�[0m
�[0;32m    qemu: fatal: [default]: FAILED! => {"cache_update_time": 1702887473, "cache_updated": false, "changed": false, "msg": "no available installation candidate for kubernetes-cni=1.2.0-2.1"}�[0m
```

**Comment by mboersma** [comment]
See discussion at https://github.com/kubernetes-sigs/image-builder/pull/1374#issuecomment-1889698355
