### ISSUE TITLE
Enforce the use of a supported Packer version

### ISSUE THREAD

**Issue by AverageMarcus** [kubernetes-sigs/image-builder#1379]
**Is your feature request related to a problem? Please describe.**

We're unable to support Packer v1.10.0+ due to https://github.com/kubernetes-sigs/image-builder/issues/1246. At time of writing, the latest version of Packer that we support is `v1.9.5` and is [what is installed](https://github.com/kubernetes-sigs/image-builder/blob/8f3ec42484d78a843bad8054fd6a7e410843bc40/images/capi/hack/ensure-packer.sh#L24) if Packer isn't found on the machine.

But if Packer `v1.10+` is found on the machine image-builder will just happily attempt to use that version which can then lead to issues such as https://github.com/kubernetes-sigs/image-builder/issues/1378

**Describe the solution you'd like**
We should restrict the version used and if v1.10+ is found we should still download `v1.9.5`. We'll need to update the Makefile also to make sure if uses the locally downloaded binary instead of the system-wide version of Packer.

**Describe alternatives you've considered**
Alternatively we could not download the version and instead show an error to the user but this means the user then needs to figure out how to downgrade their version.

**Additional context**

/kind feature

**Comment by kranurag7** [comment]
/assign 

I'll attempt hacking on this during the weekend.

**Comment by cunningr** [comment]
I am running into somewhat related issues again.  Even starting at v1.9.5 I am getting rate-limited from github when trying to install the required plugins.  Does anyone have any workarounds for this other than injected their github PAT token at build time?

**Comment by sriramandev** [comment]
@kranurag7 Are you working on this?

**Comment by sriramandev** [comment]
@kranurag7 Are you still working on this or should can I pick this up from where you left?

**Comment by kranurag7** [comment]
@sriramandev I added one commit (https://github.com/kubernetes-sigs/image-builder/pull/1383/commits/e66f4bf1f55b971e520eebcf70b094cf8d829f06)  which should be fixing the failing tests on the PR. 
If you already started working on this, let me know I'll close mine as said above. If not, a review would be great.
