### ISSUE TITLE
Support Ubuntu 24.04 LTS (Noble Numbat)

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1406]
## Describe the solution you'd like

The next long-term-support release of Ubuntu Linux will arrive at the end of April. image-builder should be ready to support it, although it may require multiple PRs and contributions or testing from several stakeholders.

## Additional context

---

/kind feature

**Comment by mboersma** [comment]
/remove-lifecycle stale

We're pretty close to calling this done!

**Comment by AverageMarcus** [comment]
@mboersma Whats outstanding on this?

**Comment by mboersma** [comment]
/close

> What's outstanding on this?

Just #1503 for OVA and RAW, but we don't need to block the epic on those. The idea was to get *most* providers to suport 24.04, and I think we're there.
