### ISSUE TITLE
flatcar qemu build broken: ssh connection failed

### ISSUE THREAD

**Issue by xinity** [kubernetes-sigs/image-builder#1445]
## Environment
- **Make target:** `make build-qemu-flatcar`
- **Run using container image? (Y/N):** Y (also tried with pure cli on the host)
- **Environment vars:**
None used
- **Vars file:**
None used

## What steps did you take and what happened?

- clone the repo
- installed the requirements
- run the make build-qemu-flatcar command

it circles until timeout with the error below:
```
2024/04/19 10:52:11 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:11 [DEBUG] Detected authentication error. Increasing handshake attempts.
2024/04/19 10:52:18 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:18 [INFO] Attempting SSH connection to 127.0.0.1:2686...
2024/04/19 10:52:18 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:18 [DEBUG] reconnecting to TCP connection for SSH
2024/04/19 10:52:18 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:18 [DEBUG] handshaking with SSH
2024/04/19 10:52:18 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:18 Keyboard interactive challenge:
2024/04/19 10:52:18 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:18 -- User:
2024/04/19 10:52:18 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:18 -- Instructions:
2024/04/19 10:52:18 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:18 -- Question 1: Password:
2024/04/19 10:52:20 packer-plugin-qemu_v1.1.0_x5.0_linux_amd64 plugin: 2024/04/19 10:52:20 [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey keyboard-interactive], no supported methods remain
```

## What did you expect to happen?
i expect the build to finish without any issue

/kind bug

**Comment by jepio** [comment]
I tried this from my Debian 12 host and from the image-builder container, both worked correctly.

My invocation is:
```
make docker-build
docker run -v $PWD/output:/home/imagebuilder/output -it --privileged -v /dev/kvm:/dev/kvm --net=host gcr.io/kinvolk-public/cluster-node-image-builder-amd64:dev build-qemu-flatcar
```
This builds Flatcar 3815.2.2 right now.

also had to ensure permissions allow the container user to interact with host volumes:
```
sudo setfacl -m u:1000:rw /dev/kvm
mkdir output
chmod 0777 output
```

Could you share a full reproducer?

Can you share

**Comment by AverageMarcus** [comment]
@jepio Out of curiosity, why do you have that local change? Could that possibly be the solution here?

**Comment by jepio** [comment]
@AverageMarcus i found that my packer install was missing the plugin, so i quickly added it to `required_plugins` instead of installing it manually on my machine

**Comment by AverageMarcus** [comment]
Is that when running in the container though? If so, that'd be a problem for everyone wouldn't it? 
I think it make sense to add it regardless as we want to move away from using the in-tree ones anyway.
