### ISSUE TITLE
Install a newer version of Packer

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#145]
Our script that installs Packer installs an older version (1.4.1), we should explore installing a newer version.

**Comment by MaxRink** [comment]
i guess this could be closed now, as its 1.5.2
https://github.com/kubernetes-sigs/image-builder/blob/817e42069bb354724764791503c6ed7a06d6d083/images/capi/hack/ensure-packer.sh#L21

**Comment by codenrhoden** [comment]
Agreed -- thank you.

/close
