### ISSUE TITLE
Install a newer version of Ansible

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#146]
Right now our scripts install Ansible version 2.8.0. We should look at using a later version.

Especially for Ansible, I think doing this requires more automated testing, because we've seen different behavior between different versions. So we have to be careful about setting our minimum version (see #143) and verifying that an existing installation works.

**Comment by moshloop** [comment]
I think it might make sense to switch to producing a docker image that bundles all the dependencies + ansible playbooks - e.g. something like https://github.com/moshloop/ansible-run and https://github.com/moshloop/ansible-dependencies. 

This would also then be a good target to release and tag for downstream consumption
