### ISSUE TITLE
Support AL2023 AMIs

### ISSUE THREAD

**Issue by dntosas** [kubernetes-sigs/image-builder#1470]
## Describe the solution you'd like
$subject ^

---

/kind feature

**Comment by AverageMarcus** [comment]
Hi @dntosas could you please provide more information as to what it is exactly you want and what you have tried so far?

What is AL2023? Is it Amazon Linux? Alpine Linux? Azure Linux? Something else?

Can you provide and links to the releases you're interested in?

**Comment by mboersma** [comment]
I think we're referring to Amazon Linux 2023: https://docs.aws.amazon.com/linux/al2023/ug/what-is-amazon-linux.html.

/cc @richardcase @sedefsavas

**Comment by richardcase** [comment]
We still need this for CAPA, so:

/reopen
/remove-lifecycle rotten
/priority important-soon
