### ISSUE TITLE
Docs and getting started 

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/image-builder#148]
Holy cow we need docs and a getting started guide and prune things we aren't using/supporting into a separate area.

**Comment by codenrhoden** [comment]
There is an mdbook within `docs/book`, and this is published to https://image-builder.sigs.k8s.io.

I can definitely add a Getting Started section to it. There are tutorials for AWS and vSphere coming in https://github.com/kubernetes-sigs/image-builder/pull/102

The actively maintained portion of this repo is pretty much all under `images/capi`. I don't have much knowledge of anything happening under `images/konfigadm` or `images/kube-deploy`. Do you know what you would want to see pruned?

**Comment by timothysc** [comment]
@codenrhoden the main github pages need links to navigate, also if we are not planning to full support some of the CLI stuff we should find a more appropriate subdir structure to denote it's state.  Right now it's front and center.

**Comment by timothysc** [comment]
@moshloop ^ are you planning to update the other sections?

**Comment by moshloop** [comment]
Yes, I will update for konfigadm and try get the CLI out as well. Still need to have a discussion with @justinsb re merging kube-deploy and konfigadm

**Comment by codenrhoden** [comment]
/remove-lifecycle stale

I think this issue can probably be closed, but leaving open to see if anything is coming for konfigadm.

**Comment by codenrhoden** [comment]
/close
This has long been taken care of.
