### ISSUE TITLE
Missing a forward slash

### ISSUE THREAD

**Issue by BobVanB** [kubernetes-sigs/image-builder#1549]
https://github.com/kubernetes-sigs/image-builder/blob/bea56f4648b95a90c0a7498f3284dccd9e95c560/images/capi/ansible/roles/sysprep/tasks/debian.yml#L52

Missing a forward slash at the start of the path.

**Comment by BobVanB** [comment]
https://github.com/kubernetes-sigs/image-builder/pull/1550

**Comment by sriramandev** [comment]
@mboersma I think this can be closed since this got fixed with #1550
