### ISSUE TITLE
Ubuntu 22.04 redirects to 22.04.1 - proxmox json needs update

### ISSUE THREAD

**Issue by nilsherzig** [kubernetes-sigs/image-builder#1560]
Sorry for not following the bug template, but I think it's not an issue with image-builder, just a needed link / checksum update. 

https://releases.ubuntu.com/releases/24.04/ redirects to 24.04.1, resulting in broken downloads from `make build-proxmox-ubuntu-2404`. Updating the `iso_url` and `iso_checksum` inside `packer/proxmox/ubuntu-2404.json` resolves this issue.

/kind bug

**Comment by AverageMarcus** [comment]
Related: https://github.com/kubernetes-sigs/image-builder/issues/1334

We've been waiting for a new patch release of Ubuntu 24.04 so we could actually pin the URLs to the immutable version (which, for some reason, isn't available when there's only a single release 🤷 )

I'll try and handle this later today (plus other providers).

**Comment by nilsherzig** [comment]
Ah sorry, I missed 1334, thanks for the fix tho. Honestly, the redirect thing on their website is kinda confusing

**Comment by nilsherzig** [comment]
Off-topic; I just found devstats.cncf.io through your profile and I love it - it's exactly as overengineered as a "cloud native" high score page should be haha. Truly beautiful
