### ISSUE TITLE
Ensure the SSM agent is installed and running in AWS images

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#158]
To enable users to log into AWS instances without an SSH bastion, the SSM agent needs to be installed and running.

This should be in all supported base images (and believe it is ok for Amazon Linux 2 and Ubuntu 18.04 already).

Related to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1553

**Comment by moshloop** [comment]
As long as this is behind a feature flag, and OFF by default it makes sense. Enabling this by default has major security implications that people may not be aware of.

**Comment by voor** [comment]
Even if the service is turned on, you require the necessary IAM permissions on the instance for it to work.  It *is* turned on by default for Amazon Linux 2 already.

**Comment by detiber** [comment]
The Ubuntu base image we are using has the ssm agent enabled by default as well, so if there is any change it would likely only be to the CentOS image if at all.
