### ISSUE TITLE
No support for ppc64le anymore

### ISSUE THREAD

**Issue by kayrus** [kubernetes-sigs/image-builder#1598]
According to the recent announcement https://groups.google.com/a/kubernetes.io/g/dev/c/LBlLCWdFN-o/m/YtGXW-qZBAAJ there is no support to build ppc64le binaries.

Our build pipeline fails trying to build a `ppc64le` image: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/cloud-provider-openstack-push-images/1845898968966369280

I was suggested to address this issue in this repo.

Please advice how can we proceed.

cc @zetaab @dulek

**Comment by kayrus** [comment]
cc @dims

**Comment by mkumatag** [comment]
@Amulyam24 can you please look at this issue?

**Comment by AverageMarcus** [comment]
We don't build any of the dependencies in this project, we just pull them from their official sources. If the kubernetes repo is no longer building artefacts for this architecture I'm afraid there's nothing we can do about it.

**Comment by AverageMarcus** [comment]
I maybe have misunderstood the issue - is the problem that image-builder itself isn't available for ppc64le or that the VM images it produced for that architecture are no longer working?

**Comment by kayrus** [comment]
I'm as a an end-user here. Last week the docker image generation worked. Since yesterday they don't. I've seen a k8s discussion about deprecating the `ppc64le` builds and noticed the same `ppc64le` in build logs and put two facts together. I asked a question the corresponding google groups, and I was forwarded here.

To be honest I have no idea what is the actual root cause, but I'd like to solve this problem as soon as possible, since 1.31.2 patch release is coming today.
