### ISSUE TITLE
capi: photon ova build needs a tdnf distro-sync

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#162]
I noticed recently that the Ansible playbooks for Photon never do a `tdnf distro-sync`. That means that we never upgrade the packages to the latest versions --  potentially missing bugfixes, security upgrades, etc. On ubuntu we do a `dist-upgrade`, and on centOS we do a `yum update`.

This is why the Photon installs are so fast. :)

I tried to quickly add this in, but ran into **all kinds** of problems. Photon seems to behave differently than other distros here. Because the `linux` package was ugpraded (changing the linux kernel version) all future `modprobe` commands fail because it's referencing the old location in `/lib/modules`. I fixed that problem with changing some ordering, but then it fails because `containerd` doesn't start up.  No idea why. 

Just wanted to capture this for posterity.

/cc @figo

**Comment by codenrhoden** [comment]
@ppadmavilasom Is there any insight you can add here?

I'd really like to be able to do a `tdnf distro-sync` as part of the normal install process with Photon, but when I do all the other steps stop working. I don't what it is about Photon that makes this happen. I'd like to avoid doing a `reboot` after the `distro-sync` if I could (I think that would solve it), but maybe that's the only way.

**Comment by ppadmavilasom** [comment]
@codenrhoden if kernel version changes, photon will require a reboot today. if we are not doing an update, we definitely should. i will look into this and update here.

**Comment by ppadmavilasom** [comment]
@codenrhoden kernel upgrades will require reboot but photon's behavior is different from other distros that it does disturb current flow till reboot. photon is planning to change this. i will follow this up. 
i wonder containerd not working is related to this (with kernel modules path changed) if not, we should understand why

**Comment by ppadmavilasom** [comment]
@codenrhoden if you copy the modules folder from the previous linux and symlink to it till you reboot, this seems to work. Not suggesting as a fix obviously.
However, the containerd startup issue you noticed might be due to this: https://github.com/kubernetes-sigs/image-builder/pull/168

**Comment by codenrhoden** [comment]
Thanks for the context and the explanation @ppadmavilasom . Sounds like there are a couple of way we could go about it. :)
