### ISSUE TITLE
Build/deploy cloud-init 19.1/2 for CentOS 7

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/image-builder#17]
This issue tracks the work necessary to automate the build of cloud-init 19.1/2 as an RPM for CentOS 7. More information on why this is necessary may be found at https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/41.

Neither [pkgs.org](https://pkgs.org/download/cloud-init) nor rpmfind listed cloud-init 18.4+ for CentOS or RHEL. There are RPMs for other OSs, but they link against python3 and other dependencies unavailable to even the CentOS EPEL repository.

There's [a branch](https://github.com/akutz/cluster-api-provider-vsphere/tree/feature/cloud-init-centos-7/hack/tools/cloud-init/centos7) of the CAPV project that includes a Dockerfile for building the cloud-init RPM for CentOS 7. More information may be found at https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/41#issuecomment-512610753.

However, during a recent call with Tim St. Clair, he mentioned possibly using [Copr](http://copr.fedorainfracloud.org) to automate the build and deployment of this package. As @codenrhoden has experience with Copr, this issue is being assigned to him.

/assign @codenrhoden

**Comment by randomvariable** [comment]
As mentioned in #21, think we also need to track AL2 as a distribution target.

**Comment by akutz** [comment]
Hi @detiber / @randomvariable,

Should we close this issue now that RHEL 7.7 and presumably CentOS 7.7 will include cloud-init 18.5? Or do we think it still makes sense to publish a fork of cloud-init?

**Comment by detiber** [comment]
I think we should probably re-purpose this to track the inclusion of the new version of cloud-init in CentOS. We might still have a reason to fork depending on Amazon Linux 2 adopting a newer version of cloud-init as well.

**Comment by codenrhoden** [comment]
Sounds like I can put #21 on hold for now, then. Perhaps I should just close it until we know if we need to do anything for AL2?

**Comment by codenrhoden** [comment]
The current CentOS cloud-init package is now 18.5 (same as CentOS 8). I'll test an image using that version instead of the Copr version soon and if all goes well, we can finally remove that customization!

**Comment by detiber** [comment]
@codenrhoden I'm planning on updating CAPA v1alpha1 to remove the use of the kubeadm module, which should remove the last blocker to removing the forked cloud-init version in this repo as well.

**Comment by detiber** [comment]
https://github.com/kubernetes-sigs/image-builder/pull/50 resolves the initial issue of shipping a forked version of cloud-init for CentOS and uses the newest version shipped with CentOS 7.7 (which is > the minimum required version of 18.4).

That said, it does not address the AL2 issue, so there is still a chance we'll need to build/install a newer version for AL2 than is available today).

**Comment by detiber** [comment]
Closing, this should no longer be necessary.
/close
