### ISSUE TITLE
Photon OVA build doesn't work with Packer 1.5.4

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#174]
I'm mostly putting this here as a note to myself to dig in deeper, but after using this project weekly for well over a year, I "accidentally" upgraded my local copy of Packer through brew, and I noticed that Photon builds no longer worked consistently. In fact it didn't work >90% of the time.

When downgrading to 1.4.1 (the version installed with `make deps-ova`), things worked fine.

I was able to see why, but did not find the code change in Packer that did it.

When Photon boots and installs from an ISO, it request an IP via DHCP. I can see in the lease file (`/var/db/vmware/vmnet-dhcpd-vmnet8.leases`) that this lease has a `uid` and a `client-hostname` associated with it. I see that when Packer looks for the IP address of the VM, it grabs the first IP address in the file with the matching MAC address.

The problem arises from the fact that once the OS install completes and the VM is rebooted, it again makes a DHCP request. This as a different `uid` in it and no `client-hostname`, so the VM gets a different IP address than the one when it was doing the OS install. Packer never re-parses the lease file, and it goes into an endless loop (well, with a **4 hour** timeout) trying to reach the VM on the incorrect IP.

When using an older version of Packer, it appears to re-parse the leases file before every attempt, and it actually picks up the most recent IP address for the expected MAC address (likely by taking the last entry in the file - but again, I haven't examined this code in Packer).

Just looking at the Packer log output (e.g. `PACKER_LOG=1`) I can see that the way it tries to reach the node is very different between the two versions, and I suspect this is very much a 1.4.x vs 1.5.x thing.

This requires more digging!

**Comment by hridayeshpawar** [comment]
Hey man I was banging my head with this problem since last night. You are right this seems to be an issue with Packer 1.5.4. 
I tried with Packer 1.4.4 and it works fine.
In version 1.5.4, with each ssh failure it is trying to reconnect with the same IP address.
But, In 1.4.4 with each failure it reparses /var/db/vmware/vmnet-dhcpd-vmnet8.leases  and I think picks the latest entry before trying to connect via ssh.

**Comment by codenrhoden** [comment]
This does appear to be fixed with Packer 1.6.0. After first I didn't think it was, because the time it takes to pick up the updated IP address varies (see comments in above referenced Packer issues), but it does eventually work.

For that reason, I think we should bump the default Packer version in our docs and install script to 1.6.0.
