### ISSUE TITLE
[capi] Building images using the k8s ci artifacts fails

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/image-builder#206]
The list of `kubernetes_imgs` that we have in `images/capi/ansible/roles/kubernetes/defaults.main.yml` includes `pause.tar`, `coredns.tar`, and `etcd.tar`, but they are not included in the k8s ci artifacts (since they are built, versioned and distributed separately).

If we want to automate loading of these images, we should likely use a separate variables for their source, type, versions rather than overloading the use of `kubernetes_http_source`, `kubernetes_semver`, and `kubernetes_source_type`

**Comment by detiber** [comment]
This is causing issues with attempting to use the k8s ci artifacts for building an image here: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/292

/assign @codenrhoden

**Comment by codenrhoden** [comment]
Discussed this topic with @detiber today.

He's going to try out adding a flag that, even when setting `kubernetes_source_type = http`, allows you to request that the images not associated with a specific K8s release ('pause', 'coredns', 'etcd') not be pre-loaded. An image built in this way would fall-back to pulling those images on-demand.
