### ISSUE TITLE
Update containerd version to v1.3.4

### ISSUE THREAD

**Issue by jiatongw** [kubernetes-sigs/image-builder#212]
The new containerd version v1.3.4 has released. (https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.3.4.linux-amd64.tar.gz) Are we going to update `containerd.json`? If so, I can make a PR for this. Thanks!

**Comment by detiber** [comment]
I created a pr for this yesterday: https://github.com/kubernetes-sigs/image-builder/pull/208

**Comment by jiatongw** [comment]
Cool!

**Comment by jiatongw** [comment]
Fixes by #208
