### ISSUE TITLE
Add link to image-builder docs to project description

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/image-builder#216]
The project description should include a link to the docs hosted at https://image-builder.sigs.k8s.io/

**Comment by codenrhoden** [comment]
I don't have the privileges to do this. Looks the ones that do are at https://github.com/kubernetes/org/blob/f713aeaafe5bb65cd5f5fe7057d52c9a08d24170/config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml#L207-L213

I'll probably ask @justinsb

**Comment by codenrhoden** [comment]
I've opened https://github.com/kubernetes/org/pull/2138 to get the admin access to resolve this.
/assign
/remove-lifecycle rotten

**Comment by mboersma** [comment]
/close

I have permissions and modified the GitHub project description so the URL points to the Image Builder Book: https://image-builder.sigs.k8s.io/
