### ISSUE TITLE
Ensure AppArmor support for distros

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#231]
Have had reports of AppArmor not being available on PhotonOS.

Not 100% certain about this, but I believe the requirements to get it to work are:

* Ensure the AppArmor module is available / loaded
* Have some profiles available on disk, though this could be done via a daemonset like https://github.com/kubernetes/kubernetes/tree/master/test/images/apparmor-loader
* If GOSS is returning in some form, probably worth some tests to ensure AppArmor is working.

Affected distributions:
* PhotonOS
* Ubuntu
* Amazon Linux 2 (which also supports SELinux)

**Comment by jessehu** [comment]
A user reported that AppArmor is not enabled.  Per K8s AppArmor doc, there should be AppArmor enabled in the node yaml, but they don’t see it:
```
kubectl get nodes -o=jsonpath=$'{range .items[*]}{@.metadata.name}: {.status.conditions[?(@.reason=="KubeletReady")].message}\n{end}'
my-cluster-control-plane-5nbhr: kubelet is posting ready status
my-cluster-md-0-86bf754697-45dp9: kubelet is posting ready status
my-cluster-md-0-86bf754697-7gdh9: kubelet is posting ready status
my-cluster-md-0-86bf754697-bzgzd: kubelet is posting ready status
```
When creating a simple “Hello AppArmor” pod with the deny-write profile https://kubernetes.io/docs/tutorials/clusters/apparmor/, the pod is in Blocked state and user see error msg "Cannot enforce AppArmor: AppArmor is not enabled on the host".
