### ISSUE TITLE
Packer 1.6+ incompatible with Goss plugin 1.0.0

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#260]
There is currently no released version of the Goss provisioner for Packer that supports 1.6.0: https://github.com/YaleUniversity/packer-provisioner-goss/issues/28

**Comment by detiber** [comment]
:grimacing:

**Comment by codenrhoden** [comment]
/close

This was my mistake. I thought I had overwritten an older version of the plugin with the new one, but I was wrong.
