### ISSUE TITLE
Use GOSS to verify that expected kernel parameters are set

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#284]
Verify that the kernel parameters that we are setting with Ansible haven't been undone/changed by later settings or custom roles. This is mainly the settings at https://github.com/kubernetes-sigs/image-builder/blob/00377e8ea77e7ad42b29bc5853eb426fce186118/images/capi/ansible/roles/node/tasks/main.yml#L33-L75

**Comment by EleanorRigby** [comment]
@codenrhoden  Can I work on this?

**Comment by EleanorRigby** [comment]
Can be closed
