### ISSUE TITLE
Deprecate use of crictl and prefer ctr instead

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/image-builder#295]
I noticed in the `goss` tests we're still testing for the presence of `crictl`, we should replace these with references to `ctr` which would remove the need to have the additional package installed.

**Comment by detiber** [comment]
`crictl` is still needed by kubeadm, I don't think we can remove the dependency without changes there as well.

**Comment by EleanorRigby** [comment]
+ also change goss commands using `crictl` to check a k8s image presence to `ctr`
