### ISSUE TITLE
Allow Applying Additional Tags to the AMI after build

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/image-builder#297]
This came from a conversation where someone requires additional tags on AMI after the packer build process.  This is tricky to do, since packer expects a map of values, but our current Makefile means of passing variables creates difficulty for adding this.

**Comment by detiber** [comment]
@voor Do you have an example of the types of tags that would be expected to be added. Is it information that would be generally useful to add, or information that is truly specific to a very specific use case?

I'm also wondering if it is unreasonable to expect adding additional tags to be something that is done as a post-task after creating the images.

**Comment by voor** [comment]
You're probably correct, that this should be a post-task, maybe a script that reads off the AMI ID that are provided in the packer manifest and adding tags based on that.

**Comment by voor** [comment]
Here's an example.  After packer runs you can take advantage of the manifest we're now generating during the build (this assumes just one AMI is created, might need to change based on use-case):

```
export AWS_AMI=`jq -rc '(.builds[0].artifact_id | split(":"))[1]' < /tmp/ami.json`
aws ec2 create-tags \
    --resources ${AWS_AMI} --tags \
    Key=Environment,Value=Development \
    Key=Foo,Value=Bar \
    Key=Name,Value='My Happy Little Image'
```
