### ISSUE TITLE
Support Ansible 2.10

### ISSUE THREAD

**Issue by dongsupark** [kubernetes-sigs/image-builder#311]
When running the image builder with Ansible 2.10 rc3, I am seeing such errors:

```
TASK [include_role : node] *****************************************************
ERROR! couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.

PLAY RECAP *********************************************************************
 The error appears to be in '.../image-builder/images/capi/ansible/roles/node/tasks/main.yml': line 37, column 3, but may
 be elsewhere in the file depending on the exact syntax problem.
 default                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

 The offending line appears to be:


 - name: Ensure net.ipv4.ip_forward sysctl is present
   ^ here
```

It seems to happen as well with other cases like `modprobe`, not only `sysctl`.
On the other hand, it works well with Ansible 2.9.11.

From a quick search, it looks like its reason is Ansible 2.10 is [migrating](https://groups.google.com/g/ansible-devel/c/oKqgCeYTs-M/m/cHrOgMw8CAAJ) many modules into other repos.
Though as Ansible newbie, I have very little idea what is going on.
FYI, according to the [roadmap](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_10.rst), Ansible 2.10 will be released in Aug 2020.

**Comment by detiber** [comment]
@dongsupark how are you installing Ansible? From what I can tell, this should only affect "ansible-base" and anyone installing the "Ansible Community Distribution" should still have access to the modules that are being moved out into collections...

I haven't followed this migration, so I may be missing something in the implementation of it, though.

**Comment by dongsupark** [comment]
I have been using Ansible 2.9.11 installed via `dnf install` on Fedora 31.

To use Ansible 2.10, I removed the rpm package for 2.9.11. (`sudo rpm -e ansible`)
Then went to my local git repo of Ansible, checked out `v2.10.0rc3`, did `sudo make install`. Then ansible 2.10 was installed under `/usr/local/`.

**Comment by detiber** [comment]
Ah, looks like that would likely result in doing the equivalent of an `ansible-base` install. You could attempt to install the rc using pip, which should be the "Ansible Community Distribution".

It looks like there is a recent release in pypy, which *should* potentially work: https://pypi.org/project/ansible/#history

**Comment by dongsupark** [comment]
No, it still does not work with a pip-installed Ansible, like:

```
pip install --user ansible-base==2.10.0rc3
```

Tried testing on different machines. Still the same.

Time to deep dive...

**Comment by dongsupark** [comment]
It works well after having installed components like below:

```
ansible-galaxy collection install ansible.posix
ansible-galaxy collection install community.general
```

We should add it to `images/capi/hack/ensure-ansible.sh`.
I will soon create a PR.

**Comment by detiber** [comment]
@dongsupark what if you did a `pip install --user ansible==2.10.0a6`? That should install the latest published pre-release of Ansible Community Distribution, which *should* include the community collections which were removed from "ansible-base"

**Comment by dongsupark** [comment]
> `pip install --user ansible==2.10.0a6`

Aha, that does the trick. Thanks!
Interesting version schemes..

**Comment by codenrhoden** [comment]
Yeah, I think I'd rather what and see what happens here after the release goes GA. I can't imagine them publishing a release where these things suddenly break, even if the repo locations underneath it all is changing.

**Comment by dongsupark** [comment]
https://github.com/kubernetes-sigs/image-builder/pull/357 was merged, and image-builder seems to already work well with Ansible 2.10.
Thanks!
