### ISSUE TITLE
centos OVA capi image can be login with root and password by default

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/image-builder#32]
**Issues description**
the centos-7 capi image can be login by user: `root` and `password` configured in ks.cfg file.

**Expected behavior**
login with password disabled by default for both custom user(`user` defined in ks.cfg) or `root`

**affected images**
`centos-7 OVA` has problem
`ubunutu-1804 OVA` **don't** have this problem
AMI images (amazon linux, ubuntu, centos) yet be tested

**Comment by akutz** [comment]
@figo and I found the issue, and he’s correcting it. It appears unique to the CentOS OVA. The root password is set in the kickstart file at https://github.com/kubernetes-sigs/image-builder/blob/53d6bcb1db9aa95f2e5d497bd1f2b9f6fae993ad/images/capi/packer/ova/linux/centos/http/7/ks.cfg#L41.

However, the root account is *also* locked via `/etc/cloud/cloud.cfg` (@figo verified `disable_root: true` is present in CentOS's `/etc/cloud/cloud.cfg`), so it’s unclear why the `root` account isn’t being locked as it is supposed to be per cloud-init’s normal boot process.
