### ISSUE TITLE
Ubuntu 18.04.4 ISO no longer available at old URL

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#348]
Now that 18.04.5 is released, the old URL to reach 18.04.4 doesn't work.

We can still access 18.04.4 at `http://old-releases.ubuntu.com/releases/18.04.4/ubuntu-18.04.4-server-amd64.iso` until we update the repo to use 18.04.5.

**Comment by ZihanJiang96** [comment]
I am looking at this issue.

**Comment by ZihanJiang96** [comment]
https://github.com/kubernetes-sigs/image-builder/pull/361 solved here
