### ISSUE TITLE
Adding mounting of bpffs in OS images

### ISSUE THREAD

**Issue by northrup** [kubernetes-sigs/image-builder#384]
As more CNI projects are moving to support BPF (eBPF) there is a genuine need to have this mounted as a prerequisite to the CNI provider starting to eliminate traffic restarts due to mounting / unmountng of the bpffs by the CNI. I would like to propose that we craft the images with the bpffs set to mount at startup. For those not using a CNI that takes advantage of BPF it shouldn't be a problem, for those that do it means that they don't have to roll their own custom images for using CAPI just to have stable BPF support

**Comment by kkeshavamurthy** [comment]
I have not checked on all OSses but on photon-3 and Ubuntu-20.04 bpf is mounted by default. 

```
builder@localhost [ ~ ]$ sudo mount |grep bpf
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
builder@localhost [ ~ ]$ cat /etc/issue
Welcome to Photon 3.0 (\m) - Kernel \r (\l)
builder@localhost [ ~ ]$

➜  ~ sudo mount |grep bpf
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
➜  ~ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l
```

**Comment by kkeshavamurthy** [comment]
no problem. I checked on Ubuntu 18.04 and it's not mounted by default. 
I do not have any objections.

**Comment by moshloop** [comment]
I am not sure that the kernels included in earlier versions have enough eBPF support to fully support these CNI's, e.g. Cilium requires 4.19.57 to support all functionality while Ubuntu 18.04 only has 4.15, Calico seems to only support 20.04+

**Comment by northrup** [comment]
🤔 thats a good point @moshloop
