### ISSUE TITLE
Unable to build qemu-ubuntu-1804 image

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/image-builder#387]
On running command `make build-qemu-ubuntu-1804`
There is error

```==> ubuntu-1804: Retrieving ISO
==> ubuntu-1804: Trying http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.4-server-amd64.iso
==> ubuntu-1804: Trying http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.4-server-amd64.iso?checksum=sha256%3Ae2ecdace33c939527cbc9e8d23576381c493b071107207d2040af72595f8990b
==> ubuntu-1804: Download failed bad response code: 404
==> ubuntu-1804: error downloading ISO: [bad response code: 404]
Build 'ubuntu-1804' errored after 1 second 762 milliseconds: error downloading ISO: [bad response code: 404]

==> Wait completed after 1 second 762 milliseconds

==> Some builds didn't complete successfully and had errors:
--> ubuntu-1804: error downloading ISO: [bad response code: 404]

==> Builds finished but no artifacts were created.
Makefile:297: recipe for target 'build-qemu- 
```

This was raised originally in [comment in capo](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/634#issue-701178952). 

Link of the release needs to be updated.

**Comment by rustycl0ck** [comment]
Same result for `make build-qemu-ubuntu-2004`
```
==> ubuntu-2004: Retrieving ISO
==> ubuntu-2004: Trying http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/ubuntu-20.04-legacy-server-amd64.iso
==> ubuntu-2004: Trying http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/ubuntu-20.04-legacy-server-amd64.iso?checksum=sha256%3A36f15879bd9dfd061cd588620a164a82972663fdd148cce1f70d57d314c21b73
==> ubuntu-2004: Download failed bad response code: 404
==> ubuntu-2004: error downloading ISO: [bad response code: 404]
Build 'ubuntu-2004' errored after 442 milliseconds 826 microseconds: error downloading ISO: [bad response code: 404]

==> Wait completed after 442 milliseconds 881 microseconds

==> Some builds didn't complete successfully and had errors:
--> ubuntu-2004: error downloading ISO: [bad response code: 404]

==> Builds finished but no artifacts were created.
```

**Comment by hidekazuna** [comment]
Maybe the reason is http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/SHA256SUMS was updated on Oct. 20th.

**Comment by prankul88** [comment]
> Same result for `make build-qemu-ubuntu-2004`
> 
> ```
> ==> ubuntu-2004: Retrieving ISO
> ==> ubuntu-2004: Trying http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/ubuntu-20.04-legacy-server-amd64.iso
> ==> ubuntu-2004: Trying http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/ubuntu-20.04-legacy-server-amd64.iso?checksum=sha256%3A36f15879bd9dfd061cd588620a164a82972663fdd148cce1f70d57d314c21b73
> ==> ubuntu-2004: Download failed bad response code: 404
> ==> ubuntu-2004: error downloading ISO: [bad response code: 404]
> Build 'ubuntu-2004' errored after 442 milliseconds 826 microseconds: error downloading ISO: [bad response code: 404]
> 
> ==> Wait completed after 442 milliseconds 881 microseconds
> 
> ==> Some builds didn't complete successfully and had errors:
> --> ubuntu-2004: error downloading ISO: [bad response code: 404]
> 
> ==> Builds finished but no artifacts were created.
> ```

Thanks for pointing it out. I will update it too.

**Comment by prankul88** [comment]
@rustycl0ck Have opened PR #435 to resolve this. PTAL
