### ISSUE TITLE
CAPI OVA: Allow custom repos in kickstart/preseed

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#40]
The current CentOS kickstart and Debian preseed files have hardcoded references to various repos (CentOS mirror, EPEL, etc). Enterprise consumers of this tool may have internal repo mirrors that they want to use instead of reaching out to the internet.

Devise a solution for these kickstart/preseed files to reference different repos instead.

**Comment by moshloop** [comment]
Should we not move the installation of most of the packages to the post-boot phase?

**Comment by codenrhoden** [comment]
> Should we not move the installation of most of the packages to the post-boot phase?

@moshloop Yes, that is exactly what we should do. I can close this issue. With #45, I made the CentOS image not rely on external repos at all, and I'm trying to do the same with Ubuntu in #47. So we went the exact opposite approach.

And there already exists a mechanism to inject custom repo definitions along with the option to disable the default system ones. So I think we are good here.

/close
