### ISSUE TITLE
Ansible 2.10.2 will break node-role

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/image-builder#412]
Ansible 2.10.2 will break the node-role as it references the RedHat_Subscription Module, which isnt bundeled in 2.10.2
Unfortunately ensure-ansible.sh left me with 2.10.2 (might be my fault)

**Comment by detiber** [comment]
Hmm, from what I can tell, it looks like it should still be included (assuming ansible community is installed and not `ansible-base`), It looks like it is in the `community.general` collection, which is included in the ansible community release: https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible.in
