### ISSUE TITLE
Azure ci flakes

### ISSUE THREAD

**Issue by kkeshavamurthy** [kubernetes-sigs/image-builder#417]
Azure ci flakes out often and one of the errors I've seen is 

[pipeline1](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/414/pull-azure-all/1316898623325212672#1:build-log.txt%3A377)
[pipeline2](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/416/pull-azure-all/1317110189899386880#1:build-log.txt%3A456)

```
 An operation is currently performing on this storage account that requires exclusive access.
make: *** [Makefile:285: build-azure-vhd-ubuntu-1804] Error 1
make: *** Waiting for unfinished jobs.... 
```

Is it because ubuntu-1804 is getting built [here](https://github.com/kubernetes-sigs/image-builder/blob/05973968701f6da08a38769e5806f436add12cbc/images/capi/packer/azure/.pipelines/build-vhd.yaml#L23) & [here](https://github.com/kubernetes-sigs/image-builder/blob/05973968701f6da08a38769e5806f436add12cbc/images/capi/packer/azure/scripts/ci-azure-e2e.sh#L61) simultaneously?

CC: @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
/assign

I need to look into this, I've seen it before as well. What's strange is that each build should be using its own storage account so there shouldn't be any conflicts. Will investigate.

cc @jsturtevant in case you have any ideas.

**Comment by CecileRobertMichon** [comment]
I think this might be because storage account name is global and the current default is
```
CREATE_TIME="$(date +%s)"
export STORAGE_ACCOUNT_NAME="capi${CREATE_TIME}"
```

So if two e2e jobs happen to be created at the same time this would fail. I'll open a PR to add a random component in the storage account name after running some validation.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage
