### ISSUE TITLE
image-build-ova.py looks to hardcode 20GB disk

### ISSUE THREAD

**Issue by lamw** [kubernetes-sigs/image-builder#428]
I successfully built Photon OS 3 OVA using K8s v1.17.11 and the only change I made from the defaults is increasing the disk capacity from 20GB to 30GB. When I tried to upload the OVA using the vSphere UI or OVFTool, it would throw an error at the very end 95% with Error 500:

```
Opening VI target: vi://administrator%40vsphere.local@192.168.30.200:443//Primp-Datacenter/host/Supermicro-Cluster/Resources/Workload
Deploying to VI: vi://administrator%40vsphere.local@192.168.30.200:443//Primp-Datacenter/host/Supermicro-Cluster/Resources/Workload
Transfer Failed
Error: Failed to transfer file [disk-0.vmdk] to host [192.168.30.14] (response code:500)
```

It took me awhile to figure out why as I have never seen this error and upon inspecting the OVA, I noticed the disk capacity was still showing 20GB. I know the Packer file did build a 30GB VMDK and browsing through the source, it looks like *image-build-ova.py* script hard codes the value of 20GB! :(

**Comment by perithompson** [comment]
@lamw I have changed to be variable in my Windows [PR](https://github.com/kubernetes-sigs/image-builder/pull/402) Once that gets merged we should be able to then alter the size easily.  There may be some work to make this a variable that you can set at run time.

**Comment by lamw** [comment]
@perithompson I see the PR you mentioned has been merged. How do I go about taking advantage of that with image-builder?

**Comment by perithompson** [comment]
Hi @lamw I hadn't put in a way to override this so I've opened a new PR, can you test this branch and let me know whether this works for your need.

**Comment by codenrhoden** [comment]
Thanks for working on this @perithompson. We had never really been concerned about the disk size because it really is only meant to capture what is needed to build the image/OVA. The disk then gets shrunk down to make the OVA as small as possible. The disk size in the OVF was never really meant to be used beyond getting the OVA loaded into the vCenter then turned into a template. When deploying/cloning the template, you can then make the disk size whatever you want.

**Comment by lamw** [comment]
@codenrhoden unfortunately, disk resize is not true currently for the TKGs offering and the disk value is indeed left hardcoded to 20GB. I was looking into this option as a way for customers to build the base image with different size disk capacity which can then be used with that service.

I've still not had success in testing the changes. Either image-builder has changed significantly from when I had reported this issue as I'm running into issues where Ansible workflows attempts to connect. I've been talking to @perithompson offline but no dice in confirming the fix

**Comment by lamw** [comment]
@perithompson I was finally able to verify the new parameter w/your branch. Looks good! 👍

**Comment by perithompson** [comment]
awesome, there was an error that meant the sizes were showing incorrectly with ovftool that I've now corrected
