### ISSUE TITLE
Ubuntu 20.04 apt update breaks DNS

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/image-builder#429]
#426 disabled ubuntu 20.04 as it started failing due to apt updates failure. This issue is to track investigating and re-enabling it.

/assign

**Comment by kkeshavamurthy** [comment]
After a reboot, the resolv.conf is populated with the search domain and everything works. 
```
packer@pkrvmfiv41tmnbe:~$ cat /etc/resolv.conf
nameserver 127.0.0.53
options edns0 trust-ad
search p1bbnpkytbnexleipe4eijnfec.xx.internal.cloudapp.net

packer@pkrvmfiv41tmnbe:~$ ping www.google.com
PING www.google.com (172.217.3.164) 56(84) bytes of data.
64 bytes from sea15s11-in-f4.1e100.net (172.217.3.164): icmp_seq=1 ttl=116 time=4.82 ms
^C
--- www.google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 4.820/4.820/4.820/0.000 ms

packer@pkrvmfiv41tmnbe:~$ sudo apt update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Fetched 317 kB in 1s (336 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
```

**Comment by kkeshavamurthy** [comment]
Looking into it a bit further, the DNS entry in resolv.conf is removed after doing a dist-upgrade. Not sure what changed with Ubuntu recently. A reboot after dist-upgrade will re-populate the dns entry and things seems to work fine.

**Comment by CecileRobertMichon** [comment]
@kkeshavamurthy are you able to repro the same thing on a simple Azure 20.04 VM not built through image-builder?

**Comment by johnsonshi** [comment]
Confirmed @kkeshavamurthy 

`apt dist-upgrade` on Ubuntu 20.04 LTS Gen 1: https://paste.ubuntu.com/p/8m5mgc8Pfc/
`apt dist-upgrade` on Ubuntu 20.04 LTS Gen 2: https://paste.ubuntu.com/p/MY37SCNGFb/

`dist-upgrade` performs an aggressive upgrade of packages in the system, and it may change dependencies, remove, or add packages along the way (see https://askubuntu.com/questions/770135/apt-full-upgrade-versus-apt-get-dist-upgrade)

Right now we need to narrow down which package is causing `resolv.conf` to be wiped during the package upgrades.

**Comment by kkeshavamurthy** [comment]
> @kkeshavamurthy are you able to repro the same thing on a simple Azure 20.04 VM not built through image-builder?

Yup. Same issue on a vanilla Ubuntu 20.04 vm. dist-upgrade messes up resolve.conf

**Comment by johnsonshi** [comment]
Confirmed @kkeshavamurthy. Just did a repro and performed `apt dist-upgrade`, and `/etc/resolv.conf` was indeed wiped on both 20.04 LTS Gen 1 and Gen 2 latest images.

`dist-upgrade` performs an aggressive upgrade of packages in the system, and it may change dependencies, remove, or add packages along the way (see https://askubuntu.com/questions/770135/apt-full-upgrade-versus-apt-get-dist-upgrade)

Right now we need to narrow down which package is causing `resolv.conf` to be wiped during the package upgrades. I'm trying to find out the culprit package.

**Comment by johnsonshi** [comment]
@CecileRobertMichon @kkeshavamurthy @anhvoms

A normal `apt upgrade` in both of the latest images for Gen 1 and Gen 2 Ubuntu 20.04 LTS *also* wipes the `/etc/resolv.conf` file.

**Comment by johnsonshi** [comment]
An `apt dist-upgrade` or even a normal `apt upgrade` does not overwrite the `/etc/resolv.conf` file in Ubuntu 18.04.

**Comment by johnsonshi** [comment]
Alright I've managed to isolate what circumstances `/etc/resolv.conf` gets overwritten.

On Ubuntu, `resolv.conf` and network name resolution is handled by `systemd-resolved`, which is a component service of `systemd`.

On the latest Ubuntu 20.04 images, @kkeshavamurthy reported that performing an `apt dist-upgrade` caused the `/etc/resolv.conf` file to be overwritten (causing the `search` option for to disappear within the file, which breaks DNS). I also tried performing a simple `apt upgrade`, which also caused `/etc/resolv.conf` to be overwritten.

I inspected which packages are upgradable to narrow down the culprit package. Two upgradable packages that were likely culprits were `netplan.io` and `systemd`.

Upgrading `netplan.io` only does not cause `/etc/resolv.conf` to be overwritten (see https://paste.ubuntu.com/p/NHQ7Wv37mC/)

Upgrading `systemd` only causes `/etc/resolv.conf` to be overwritten (see https://paste.ubuntu.com/p/36xbMMxYqm/).

I deployed an old Ubuntu 18.04 LTS image (with an out-of-date `systemd` package). I upgraded `systemd` on that image but it didn't overwrite `/etc/resolv.conf`.

This issue seems constrained to the latest Ubuntu 20.04 Gen 1 and Gen 2 images when `systemd` is upgraded. We'll work with upstream Canonical and internal teams to fix this bug upstream.

**Comment by johnsonshi** [comment]
I've further narrowed down the faulty upgrade. The symptom (`/etc/resolv.conf` overwritten) only exhibits itself on a very specific upgrade path.

On an older Ubuntu 20.04 LTS Gen 1 VM Image:
* Canonical:0001-com-ubuntu-server-focal:20_04-lts:**_20.04.202006270_**
* Upgrade of systemd: systemd/**_focal-updates_** **_245.4-4ubuntu3.3_** amd64 [upgradable from: **_245.4-4ubuntu3.1_**]
* `/etc/resolv.conf` **_is not overwritten_** when `systemd` goes through that upgrade.
* https://paste.ubuntu.com/p/7frQfgTXkf/

On a recent Ubuntu 20.04 LTS Gen 1 VM Image:
* Canonical:0001-com-ubuntu-server-focal:20_04-lts:**_20.04.202010260_**
* Upgrade of systemd: systemd/**_focal-updates_** **_245.4-4ubuntu3.3_** amd64 [upgradable from: **_245.4-4ubuntu3.2_**]
* `/etc/resolv.conf` **_is overwritten_** when `systemd` goes through that upgrade.
* https://paste.ubuntu.com/p/NmXb4PKj3f/

Seems like upgrading from `systemd 245.4-4ubuntu3.2` to `systemd 245.4-4ubuntu3.3` (from the focal-updates repo) causes `/etc/resolv.conf` to be overwritten, which causes `/etc/resolv.conf` to not have the `search` option, which causes DNS to break.

**Comment by johnsonshi** [comment]
@linuxelf001 Hey Rakesh, has upstream Canonical rolled out a `systemd` fix to the Ubuntu images? `apt update` is a very common scenario that users run when bootstrapping and setting up a VM, so this bug may have a very big impact.

**Comment by linuxelf001** [comment]
Hi @johnsonshi, not yet. One workaround at this time is to reboot the VM before upgrading the systemd package. If reboot is done, then the DNS search entry is not touched in resolv.conf file. 

Issue is reported/discussed here - https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1902960.

**Comment by kkeshavamurthy** [comment]
The new image seems to be working fine. I was able to build Ubuntu 20.04 VHD without hitting the DNS issue. @CecileRobertMichon +1 to turn CI for Ubuntu 20.04 back on.

**Comment by CecileRobertMichon** [comment]
Awesome, @kkeshavamurthy want to open the PR?
