### ISSUE TITLE
kernel modules for baremetal missing

### ISSUE THREAD

**Issue by szengerle** [kubernetes-sigs/image-builder#458]
Same Ubuntu preseed.cfg file is used for OVA and QEMU builds. QEMU builders qcow2's are suitable for bare metal deployments if linux-generic would be used insted of linux-virtual. I needed for example the `hpsa` modules for my bare metal deployment. For my builds I commented out the respective line:
`d-i base-installer/kernel/override-image string linux-virtual `

Does it make sense to use linux-generic instead of linux-virtual for QEMU builds?

Br
Sebastian

**Comment by detiber** [comment]
Ideally, I think it would be great if it was configurable at build time to use either `linux-virtual` or `linux-generic`, similar with the RHEL, CentOS, and Photon alternatives

**Comment by detiber** [comment]
@szengerle You should be able to use the newly introduced "raw" images for this purpose now, It's a separate target for now, since I wasn't sure if we'd need to add additional changes, but we can always consolidate it down later if we don't need it.
/close
