### ISSUE TITLE
After growroot new build ova ubuntu 20.04, hangs in busybox.

### ISSUE THREAD

**Issue by farodin91** [kubernetes-sigs/image-builder#464]
We are build our images based on the newest commit of the head branch using vsphere.

The build went through and afterwards cluster-api clones the image. Cluster-api powers on the machine the grow happens than it hangs on following screen: 
![image](https://user-images.githubusercontent.com/1159212/102785194-d8228700-439d-11eb-8327-ee98471e519b.png)

If restart the image everything works fine afterward. the machine has a correct formated disk and the kubeadm join works fine.

Any idea?

**Comment by darc1** [comment]
I got the same error using Ubuntu 20.04. If I reset the VM manually after getting to this menu, it boots as expected.

**Comment by kkeshavamurthy** [comment]
I'm seeing this issue as well.
Thanks to @EleanorRigby for debugging this. Seems like if the ova HD size is changed from 20Gb, this issue occurs. We spun up a bunch of VMs with the original 20Gb as the clone VM HD size and all VMs booted up fine. 
All the VMs with HD size different from 20Gb, drops into `initramfs` on first boot.
