### ISSUE TITLE
Add upload support for ova into vcenter

### ISSUE THREAD

**Issue by farodin91** [kubernetes-sigs/image-builder#468]
We are using the image builder internally. We have automated the upload process into our vcenter after building a new image.

We are using govc:
```py
def setup_govc_env(vsphere_data):
    os.environ[
        "GOVC_URL"] = f'https://{vsphere_data["vsphere_username"]}@{vsphere_data["vsphere_vcenter_server"]}/sdk'
    os.environ["GOVC_PASSWORD"] = vsphere_data["vsphere_password"]
    os.environ["GOVC_INSECURE"] = vsphere_data["vsphere_insecure_connection"]
    os.environ["GOVC_DATACENTER"] = vsphere_data["vsphere_datacenter"]


def export_ova_spec(path, spec_path, vsphere_data):
    print("image-build-ova: export ova spec from %s to %s" % (path, spec_path))
    output = subprocess.check_output(["/usr/sbin/govc", "import.spec", path])
    spec = json.loads(output)
    spec["NetworkMapping"][0]["Network"] = vsphere_data["vsphere_network"]
    spec["DiskProvisioning"] = "thin"
    print(f"json spec: {json.dumps(spec)}")
    with open(spec_path, 'w') as f:
        f.write(json.dumps(spec))


def upload_ova(template_name, path, spec_path, vsphere_data):
    full_name=f'/{vsphere_data["vsphere_datacenter"]}/vm/{vsphere_data["vsphere_folder"]}/{template_name}'
    print("image-build-ova: upload ova %s" % full_name)
    args = ['/usr/sbin/govc', 'vm.destroy', full_name]
    subprocess.check_output(args)
    args = ['/usr/sbin/govc', 'import.ova',
            f'-ds={vsphere_data["vsphere_datastore"]}',
            f'-pool={vsphere_data["vsphere_cluster"]}/Resources',
            f'-folder=/{vsphere_data["vsphere_datacenter"]}/vm/{vsphere_data["vsphere_folder"]}',
            f'-name={template_name}',
            f'-options={spec_path}',
            path]
    subprocess.check_output(args)
    args = ['/usr/sbin/govc', 'snapshot.create', f'-vm={full_name}', 'root']
    subprocess.check_output(args)
    args = ['/usr/sbin/govc', 'vm.markastemplate', full_name]
    subprocess.check_output(args)
```

**Comment by farodin91** [comment]
@codenrhoden What do you think about this tooling?

**Comment by codenrhoden** [comment]
/remove-lifecycle stale

I'd definitely like to keep this issue around...
Ultimately I'd like it if this step wasn't necessary -- if we are just putting the OVA back into the same vCenter that built the machine image anyways, is there a way to create the template without having to download the disk, and then re-upload the final OVA?

It seems the answer is yes, but not sure at this point how easy that is to accomplish with the current Packer post-processor tooling. Ultimately what we need/want in vCenter is a template (for consumption by CAPV), which Packer can create (`"convert_to_template"': "true"`), but we also need to be able to set all the vApp properties that are currently set in the OVF XML -- that's what is missing. There are vCenter APIs to do this, but this missing link is how/what to call to do so.

But with that in place, all of the steps of downloading the VMDK, creating an OVF/OVA, and then re-uploading become unnecessary.

**Comment by cprivite** [comment]
Yeah, for our use case, we don't even need new code, just some readjustment of the config file structuring so you can have packer create the template on vSphere and be done. No further downloading, uploading, or anything else with ova files needed.

**Comment by codenrhoden** [comment]
@cprivite Do you see a way to restructure the Packer config file to accomplish this? I haven't seen a way so far.

The problem as I see it is that the `export` section for a `vsphere-iso` Packer builder doesn't have a flag to enable/disable. So long as the `export` section is there, it will download the VM disk. Ideally I would want to be able to toggle this section off in the scenario where we are happy to just end up with a template in vCenter. So far we've only been able to toggle the downloading of the OVF manifest.

https://www.packer.io/docs/builders/vmware/vsphere-iso#export-configuration

This is one of many reasons why the project may need a Packer pre-processor -- one that takes input and *generates* the Packer config for us. The Packer config as it is is very limiting.
