### ISSUE TITLE
OVA Windows Image Builder unable to create ovf

### ISSUE THREAD

**Issue by perithompson** [kubernetes-sigs/image-builder#508]
**What steps did you take and what happened:**
Trying to build Windows OVA using vmware-local or vsphere builders results the following errors due to changes in the image-build-ova.py script.  I made a change on Error 1 to add the changes to the packer-windows.json file

1. Added in [PR](https://github.com/kubernetes-sigs/image-builder/pull/467)
```
==> vmware-iso (shell-local): Traceback (most recent call last):
==> vmware-iso (shell-local):   File "./hack/image-build-ova.py", line 270, in <module>
==> vmware-iso (shell-local):     main()
==> vmware-iso (shell-local):   File "./hack/image-build-ova.py", line 77, in main
==> vmware-iso (shell-local):     with io.open(args.ovf_template, 'r', encoding='utf-8') as f:
==> vmware-iso (shell-local): FileNotFoundError: [Errno 2] No such file or directory: '../../hack/ovf_template.xml'
Build 'vmware-iso' errored after 38 minutes 1 second: 1 error(s) occurred:

* Post-processor failed: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
```

2. This seems to have been changed by this [PR](https://github.com/kubernetes-sigs/image-builder/pull/470)
```
==> vmware-iso (shell-local): Traceback (most recent call last):
==> vmware-iso (shell-local):   File "./hack/image-build-ova.py", line 270, in <module>
==> vmware-iso (shell-local):     main()
==> vmware-iso (shell-local):   File "./hack/image-build-ova.py", line 141, in main
==> vmware-iso (shell-local):     'DISTRO_NAME': build_data['distro_name'],
==> vmware-iso (shell-local): KeyError: 'distro_name'
Build 'vmware-iso' errored after 40 minutes 43 seconds: 1 error(s) occurred:

* Post-processor failed: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
```

**What did you expect to happen:**
Image ova should generate successfully

**Anything else you would like to add:**
I think we need to work out a way to ensure that changes can be reviewed for windows as the builders are different from different Linux distros but are intertwined 

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): Windows
- Packer Version: 
- Packer Provider: OVA
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug 
/sig windows
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jayunit100** [comment]
cc @kkeshavamurthy any thoughts on what we can do to fix this one?

**Comment by kkeshavamurthy** [comment]
For error2:
You'll need to have `distro_name/arch/version` in your `windows-x.json` similar to this
https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/ova/ubuntu-2004.json#L3

**Comment by kkeshavamurthy** [comment]
For error1:
the calling of the `image-build-ova.py` needs to change to include `--ovf-template` arg. Similar to 
https://github.com/kubernetes-sigs/image-builder/blob/b72dae811bbb42d7ee03c44c942aa54865eb586e/images/capi/packer/ova/packer-windows.json#L190
for all builders

**Comment by perithompson** [comment]
ok ill try and add these in, thanks @kkeshavamurthy i am about to open a PR so ill just include these changes
