### ISSUE TITLE
Allow building windows images without wins installed

### ISSUE THREAD

**Issue by perithompson** [kubernetes-sigs/image-builder#523]
**Is your feature request related to a problem?**
Wins is used to workaround the need for privileged containers in windows and allows for kube-proxy and other cnis to run on host.  However because this allows for scheduling workloads on the host, this can be considered insecure by some user and it would be useful to be able to skip the install of this 

**Describe the solution you'd like**
Provide a variable to skip the wins installation

/kind feature
/sig windows

**Comment by perithompson** [comment]
cc @jayunit100 @jsturtevant

**Comment by jsturtevant** [comment]
If the value of the wins url is empty it will skip installing:

https://github.com/kubernetes-sigs/image-builder/blob/f3cf15924a9dfe360437469f729d580114e62e3f/images/capi/ansible/windows/node_windows.yml#L22-L24

Intent was once Privileged containers lands to no longer require wins.exe.
