### ISSUE TITLE
Flaky behaviour when updating windows defender signatures

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/image-builder#549]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Sometimes the following request fails during ci:

https://github.com/kubernetes-sigs/image-builder/blob/a73be46a64ee82e329838689306a4c77625ac367/images/capi/ansible/windows/roles/systemprep/tasks/main.yml#L66-L68

**What did you expect to happen:**
defender signatures update with no error

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

https://github.com/kubernetes-sigs/image-builder/pull/548#issuecomment-800564643

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
/sig windows
/assign

**Comment by jsturtevant** [comment]
error message is:

> [0;32m    vhd-windows-2004: fatal: [default]: FAILED! => {"changed": true, "cmd": "# https://github.com/microsoft/azure-pipelines-image-generation/pull/1259/files\n$service = Get-Service \"Windefend\"\n$service.WaitForStatus(\"Running\",\"00:5:00\")\nUpdate-MpSignature", "delta": "0:00:15.324964", "end": "2021-03-16 05:57:32.287716", "msg": "non-zero return code", "rc": 1, "start": "2021-03-16 05:57:16.962752", "stderr": "Update-MpSignature : The remote procedure call failed. \r\nAt line:4 char:1\r\n+ Update-MpSignature\r\n+ ~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (MSFT_MpSignature:ROOT\\Microsoft\\...SFT_MpSignature) [Update-MpSignature], \r\n    CimException\r\n    + FullyQualifiedErrorId : HRESULT 0x800706be,Update-MpSignature", "stderr_lines": ["Update-MpSignature : The remote procedure call failed. ", "At line:4 char:1", "+ Update-MpSignature", "+ ~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (MSFT_MpSignature:ROOT\\Microsoft\\...SFT_MpSignature) [Update-MpSignature], ", "    CimException", "    + FullyQualifiedErrorId : HRESULT 0x800706be,Update-MpSignature"], "stdout": "",

**Comment by perithompson** [comment]
@jsturtevant could we add a retry to help with this?  I've encountered this too 
```
 retries: 3
 delay: 3
```

or even a timeout?

**Comment by perithompson** [comment]
I don't mind taking a look into this if you want

**Comment by jsturtevant** [comment]
We can open a PR with the retries and see if that improves it.  I also was requested by the Defender team to grab some logs

**Comment by jsturtevant** [comment]
if you reproduce it locally (i've had a hard time) could you grab the logs with `%programfiles%\Windows Defender\MpCmdRun -GetFiles`?

**Comment by perithompson** [comment]
I'll sure give it a go, ive only seen this when running off my machine, I'll have to stop it from deleting, looks like you managed to repro last night though?

**Comment by jsturtevant** [comment]
Yes got a repo yesterday. It looks like the Updates component https://github.com/kubernetes-sigs/image-builder/blob/df3b27b0ec0a3d58141ea59292515c5e515d9b29/images/capi/ansible/windows/roles/systemprep/tasks/main.yml#L35 is scheduling an update of the signatures asynchronously as a windows scheduled task.  Since that is already running the call to update date the signature fails (which no error message). I think this explains why it happens more times than other (when an image from the market place is older and needs signature updates) and why retries does seem to resolve the issue.

I am waiting to hear back from the Defender team on best way to handle this but I see two options: 

- move the signature update prior to calling updates 
- check for an already signature update is already running.

**Comment by perithompson** [comment]
I think moving before makes a lot of sense actually or even removing https://github.com/kubernetes-sigs/image-builder/blob/d6a2b02d28efc97c5bc2dd77e912d51998c8f0f5/images/capi/ansible/windows/roles/systemprep/tasks/main.yml#L43
 might be enough

**Comment by jsturtevant** [comment]
I spoke with the Defender team and it turns out the defender service will automatically trigger updates if it needs them. This is why we see this periodically... the Azure market place images will start to go stale with old definitions based on various factors and the defender service will kick off the updates when it comes online. 

Since the images are built and then deployed at a later time the definitions will almost always be out of date.  The defender service has the logic already built into it to update these when required and which means when a node first comes online after deployment it will almost always do an update making our manually triggered updates here not necessary.  

If we remove this section all together I think we will be in better shape.  Thoughts?

**Comment by perithompson** [comment]
I think you may be right on the money, as the windows defender updates will most likely happen automatically when the node boots up at runtime I don't think we need the explicit step. I'm happy for the step to go as well
