### ISSUE TITLE
Developer Tools on Windows images

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/image-builder#551]
**Is your feature request related to a problem? Please describe.**

We need to have a baseline of administrative tools installed on machines:
- vim 
- others?

**Describe the solution you'd like**

A dev-tools/ or admin-tools/ ansible directory where we can add dev tools

(at a minimum a powershell script to bootstrap this stuff would be good) 

**Additional context**

/kind feature

**Comment by perithompson** [comment]
@jsturtevant I remember that in early commits you were using chocolatey but you stopped, was there any reason, I think this would be used to install vim with ansible, any thoughts or concerns?
