### ISSUE TITLE
Remove need for vSphere to build ova with vSphere provider

### ISSUE THREAD

**Issue by vignesh-goutham** [kubernetes-sigs/image-builder#552]
**Is your feature request related to a problem? Please describe.**
While trying to build an ova for vSphere capi provider, it looks like it requires access to an active vSphere. I'm trying to understand this hard dependency.  

**Describe the solution you'd like**
I'd like vSphere image builder to run image builds without the need for vSphere. Built images could end up in local filesystems. Or atleast if the image-builder is designed to require a hypervisor to build, it could connect to local virtualbox or qemu and produce a vsphere capi vm image.

/kind feature

**Comment by perithompson** [comment]
Hi @vignesh-goutham you can also build using vmware fusion or vmware workstation using `make build-node-ova-local-base-ubuntu-2004` this will then allow you to import the OVA to vsphere after it has completed?

**Comment by vignesh-goutham** [comment]
Thank you for that information. That helps!
