### ISSUE TITLE
CAPI VMware image builder doesn't acknowledge resource_pool

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/image-builder#567]
**What steps did you take and what happened:**
```
{
	"vcenter_server": "hostname",
	"username": "administrator@vsphere.local",
	"password": "password",
	"template": "ubuntu-1804-kube-v1.20.1",
	"datacenter": "dc",
	"cluster": "cluster",
	"insecure_connection": "true",
	"datastore": "CAPI_DS",
	"network": "OtherVM-462",
	"resource_pool": "ClusterAPI"
}

[kbreit@e4cent0dev1 capi]$ PACKER_VAR_FILES=config.json make build-node-ova-vsphere-clone-ubuntu-2004
hack/ensure-ansible.sh
hack/ensure-ansible-windows.sh
hack/ensure-packer.sh
hack/ensure-goss.sh
Right version of binary present
hack/ensure-ovftool.sh
packer build -var-file="/home/kbreit/image-builder/images/capi/packer/config/kubernetes.json"  -var-file="/home/kbreit/image-builder/images/capi/packer/config/cni.json"  -var-file="/home/kbreit/image-builder/images/capi/packer/config/containerd.json"  -var-file="/home/kbreit/image-builder/images/capi/packer/config/ansible-args.json"  -var-file="/home/kbreit/image-builder/images/capi/packer/config/goss-args.json"  -var-file="/home/kbreit/image-builder/images/capi/packer/config/common.json"  -color=true -var-file="packer/ova/packer-common.json" -var-file="/home/kbreit/image-builder/images/capi/packer/ova/ubuntu-2004.json" -var-file="packer/ova/vsphere.json" -except=esx -except=local -only=vsphere-clone -var-file="/home/kbreit/image-builder/images/capi/config.json"  packer/ova/packer-node.json
vsphere-clone: output will be in this color.

==> vsphere-clone: Cloning VM...
Build 'vsphere-clone' errored after 145 milliseconds 252 microseconds: Error finding resource pool: resource pool 'cluster/Resources/' not found
```

**What did you expect to happen:**
I expected it to use cluster/ClusterAPI.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I was able to resolve this by adding `resource_pool` keys in `packer-node.json` wherever `vcenter_server` was referenced. `"resource_pool": "{{user `resource_pool`}}",`

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version: 1.6.6
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by kbreit** [comment]
Bump

**Comment by Heiko-san** [comment]
/reopen

As I understand you closed this unfixed because of missing contributors.
We didn't find what exactly is wrong with the string.
But actually this seems to fix it:

```
jq '.|.builders[].resource_pool = "{{user `resource_pool`}}"' /home/imagebuilder/packer/ova/packer-node.json
```

It seems to be the same string as already in place however (?)
