### ISSUE TITLE
windows: add a 'failed_when' hook into the openssh task 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/image-builder#588]
**What steps did you take and what happened:**

OpenSSH installation can fail for example in some cases ( i think this happened to me when i had a product key or internet acces error, but dont remember the exact details) 
```
# Requires admin rights to install 
# https://docs.ansible.com/ansible/latest/user_guide/become.html#become-and-windows
- name: Install OpenSSH
  win_shell: Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
  become: yes
  become_method: runas
  become_user: SYSTEM
  # Lets add this ...........
  failed_when:  ???
```
Later steps then fail for other obvious reasons, for example, 

**What did you expect to happen:**

If openssh install failed , that would be detected explicitly by image builder

(this is minor but a good first issue for someone interested in learning how image-builder windows works - but i think it would be a nice thing to have as im sure folks will run into my issue at some point once more people outside of public clouds begin using image builder for windows)

**Comment by perithompson** [comment]
Usually, this fails if you are missing required windows updates? did you run windows update in your image?

**Comment by perithompson** [comment]
maybe there is some check we could put in that will fail with a graceful error if the windows version doesn't meet the minimum by this step, I don't support /cc @jsturtevant  knows what the min version of 2019 supports this feature?  that would be a good check?

**Comment by jsturtevant** [comment]
Is there an error message that it failes with?  I think that would be need to for the `failed_when` clause.  

I have not seen this failure before.  The support for SSH goes way back several years for support in WS 2019, so not sure if that would be an issue...

**Comment by jsturtevant** [comment]
interestingly this failed in [CI](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/600/pull-azure-vhds/1385302383067664384) today but it wasn't a silent failure:


```
[0;32m    vhd-windows-2004: An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)[0m
[0;32m    vhd-windows-2004: fatal: [default]: FAILED! => {"changed": false, "msg": "internal error: failed to 
become user 'SYSTEM': Exception calling \"CreateProcessAsUser\" with \"9\" argument(s): 
\"CreateProcessWithTokenW() failed (Access is denied, Win32ErrorCode 5)\""}
[0m
[0;32m    vhd-windows-2004:[0m
[0;32m    vhd-windows-2004: PLAY RECAP *********************************************************************[0m
[0;32m    vhd-windows-2004: default                    : ok=7    changed=4    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0[0m
```
