### ISSUE TITLE
Improve UX for PR tests

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/image-builder#589]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

It's currently hard to tell which test failed and why when looking at the logs for azure PR tests, eg. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_image-builder/585/pull-azure-vhds/1381615892579749888

I usually end up searching for "failed" or "error" in the logs to know which packer buid failed and why it failed. It would be great to have some sort of overall summary either using junit (not sure how feasible that is) or via a high level summary at the end. 

**Describe alternatives you've considered**

**Additional context**

/kind feature

**Comment by codenrhoden** [comment]
/remove-lifecycle rotten
I'll address the latest comments on #736 so we can get this one closed out.

**Comment by codenrhoden** [comment]
I think this is addressed for Azure in #736, and in vSphere with #872.

/close
