### ISSUE TITLE
Add retry logic for kubernetes binary url based downloads

### ISSUE THREAD

**Issue by vrabbi** [kubernetes-sigs/image-builder#595]
**Is your feature request related to a problem? Please describe.**
When using the url.yaml method for installijg k8s binaries on images no retry logic is present. It can be very common to have sporadic network or server issues which make a download fail. Adding retry logic similar to that in k8s component containers task would be very helpful and would limit the failed builds which i have encountered multiple times.

**Describe the solution you'd like**
Add retry logic to all the download tasks in url.yaml playbook

**Describe alternatives you've considered**
I have added locally retry logic and that works for me now but i think this should be done in the upstream project.

**Additional context**
I am using tkg and therefore need to use the url based downloads as that is the supported method with tkg.

/kind feature

**Comment by perithompson** [comment]
Thanks for submitting this! I think this is a good spot! how has your testing gone with adding the retry logic?

**Comment by vrabbi** [comment]
I have been using it with no issues at all however i have only used it for capv ubuntu 20.04 and 4 k8s versions. It probably meeds to be validated against other providers,os and k8s versions to make sure. Next wrek when i am back in the office i can share the changes i made and create a pr if that would be helpful
