### ISSUE TITLE
Automatic updates for Windows are running even though we disabled them

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/image-builder#599]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Windows updates are disabled: https://github.com/kubernetes-sigs/image-builder/blob/212059706cb1b319c5dcdc39752048fb41e2cb54/images/capi/ansible/windows/roles/systemprep/tasks/main.yml#L15-L21

but on a cluster that has been up for awhile they are still updating:

Creation date:
```
Operation name
Create or Update Virtual Machine
Time stamp
Mon Apr 19 2021 14:11:04 GMT-0700 (Pacific Daylight Time)
```

Upgrade dates:
```
PS C:\Users\capi> wmic qfe list
Caption                                     CSName        Description      FixComments  HotFixID   InstallDate  InstalledBy          InstalledOn  Name  ServicePackInEffect  Status
http://support.microsoft.com/?kbid=4601558  test-2-nfdf5  Update                        KB4601558               NT AUTHORITY\SYSTEM  4/21/2021
http://support.microsoft.com/?kbid=4535680  test-2-nfdf5  Security Update               KB4535680               NT AUTHORITY\SYSTEM  4/21/2021
https://support.microsoft.com/help/4589208  test-2-nfdf5  Update                        KB4589208               NT AUTHORITY\SYSTEM  4/21/2021
https://support.microsoft.com/help/5000859  test-2-nfdf5  Security Update               KB5000859                                    3/3/2021
https://support.microsoft.com/help/5001404  test-2-nfdf5  Security Update               KB5001404               NT AUTHORITY\SYSTEM  4/21/2021
https://support.microsoft.com/help/5001342  test-2-nfdf5  Security Update               KB5001342               NT AUTHORITY\SYSTEM  4/22/2021
```

**What did you expect to happen:**
Update to not be applied until manually run.  It is recommended to not auto upgrade Windows patches before running tests due to past issues with breaking changes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jsturtevant** [comment]
Checking the registry values I see an extra parameter which indicates that they are scheduled in the background:

```
Get-ItemProperty HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU


AUOptions    : 4
NoAutoUpdate : 1
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
PSChildName  : AU
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
```

From https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#configuring-automatic-updates-by-editing-the-registry:

> AUOptions (REG_DWORD):

    1: Keep my computer up to date is disabled in Automatic Updates.

    2: Notify of download and installation.

    3: Automatically download and notify of installation.

    4: Automatically download and scheduled installation.

On a machine that doesn't auto update I don't see the value 4 for `AUOptions`:

```
PS C:\Users\azureuser> Get-ItemProperty HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU 


NoAutoUpdate : 1
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU 
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate    
PSChildName  : AU
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry
```

**Comment by perithompson** [comment]
I just started to see errors setting up OpenSSH Server this with the Feb2021 window 2019 media, this has only just started happening and was working fine before?

TASK [systemprep : Install OpenSSH] ********************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "Get-WindowsCapability -Online -Name OpenSSH.Server* | Add-WindowsCapability -Online", "delta": "0:00:08.388772", "end": "2021-04-30 10:58:33.105127", "msg": "non-zero return code", "rc": 1, "start": "2021-04-30 10:58:24.716355", "stderr": "Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950\r\nAt line:1 char:119\r\n+ ... ability -Online -Name OpenSSH.Server* | Add-WindowsCapability -Online\r\n+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException\r\n    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand", "stderr_lines": ["Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950", "At line:1 char:119", "+ ... ability -Online -Name OpenSSH.Server* | Add-WindowsCapability -Online", "+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException", "    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand"], "stdout": "", "stdout_lines": []}
