### ISSUE TITLE
Buidling OS X OVAs fails due to concurrency issue

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/image-builder#601]
**What steps did you take and what happened:**

built a windows iso using `make build-node-ova-local-windows-2019`  I got an error:

```
    vmware-iso: objc[77717]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
    vmware-iso: objc[77717]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
    vmware-iso: ERROR! A worker was found in a dead state
```

**What did you expect to happen:**

ova was built w/o a weird objc error :)

**Anything else you would like to add:**

Workaround i think is to do 

```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

Maybe we should add that somehow to the ansible stuff if theres an os x specific excution path ? 

**Environment**

OS X Mojave
Python 3.9 (this bug exists on multiple python versions though i think, not specific to 3.9.x) or anything

**Comment by jsturtevant** [comment]
Does this only happen on OS X? There are things in the code to handle special cases: https://github.com/kubernetes-sigs/image-builder/blob/212059706cb1b319c5dcdc39752048fb41e2cb54/images/capi/hack/ensure-ansible-windows.sh#L27  

Is this limited to only the Windows builds or also Linux vms?
