### ISSUE TITLE
Windows containerd should crictl to pull image to ensure unused files are cleaned up in containerd

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/image-builder#640]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**
Right now Windows containerd uses ctr.exe to pull images. This results in large footprint additional files left behind on containerd.

containerd config should have `discard_unpacked_layers=true` and we should use crictl (which respects that value) to clean up space.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Change ctr.exe to crictil.exe (requires installing crictl)

https://github.com/kubernetes-sigs/image-builder/blob/dfc23becf09d0c51643405210841cc1955429ac6/images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml#L103

add `discard_unpacked_layers=true` to https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/windows/roles/runtimes/templates/config.toml
**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
/sig windows

fyi @perithompson

**Comment by perithompson** [comment]
I don't think we download crictl.exe at the moment do we, although we should! good catch @jsturtevant

**Comment by jsturtevant** [comment]
credit to @mainred and @dcantah

**Comment by jsturtevant** [comment]
/remove-lifecycle stale

cc: @knabben
