### ISSUE TITLE
Add Image-builder support for Photon OS 4

### ISSUE THREAD

**Issue by MnrGreg** [kubernetes-sigs/image-builder#649]
**Describe the solution you'd like**
Ability to build Photon OS 4 images so that the new features such as `Wireguard` can be leveraged

**Additional context**
https://www.tigera.io/blog/introducing-wireguard-encryption-with-calico/
https://github.com/vmware/photon/blob/c361dcc0c20934f6c1bd075864e425a53dc7dc94/SPECS/linux/linux.spec#L738

/kind feature

**Comment by ubhide** [comment]
Refreshing this, as it would be useful.

/remove-lifecycle rotten
