### ISSUE TITLE
Windows image build fails as ansible win_template module fails with FileNotFoundError

### ISSUE THREAD

**Issue by outofmem0ry** [kubernetes-sigs/image-builder#668]
**What steps did you take and what happened:**
Followed the instructions to create a Windows image but the image building process failed with an error 
```
fatal: [default]: FAILED! => {"changed": false, "msg": "FileNotFoundError: 
[Errno 2] No such file or directory: b'C:\\\\Program Files\\\\Cloudbase Solutions\\\\Cloudbase-Init\\\\conf\\\\cloudbase-init-unattend.conf'"}
```

**Anything else you would like to add:**
After some research on the issue looks like this was first fixed by https://github.com/kubernetes-sigs/image-builder/pull/624 and later reverted by https://github.com/kubernetes-sigs/image-builder/pull/657 removing ansible-base and eventually reverting the ansible version to `2.10.0` which still appears to have this problem. Temporarily worked around it by updating the [version](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/hack/ensure-ansible.sh#L25 ) to `2.9.24`. 

I haven't tested with other 2.10.x versions but plan to do so.

- Packer Version: Packer v1.7.2

/kind bug

**Comment by perithompson** [comment]
@jsturtevant I guess the ansible-galaxy update hasn't worked for everyone?  I've had a couple of reports so I wonder if this is OS-dependent or something

**Comment by jsturtevant** [comment]
@outofmem0ry could you check that you have the correct windows package by running: `ansible-galaxy collection list ansible.windows`?

**Comment by mboersma** [comment]
I ran into the same problem, and after a lot of thrashing around found that updating ansible to 4.2.0 and installing ansible.windows explicitly seemed to work. YMMV of course, but here's the change I made in case it helps: https://github.com/deis/docker-go-dev/pull/307/files

**Comment by knabben** [comment]
If you have ansible installed in the path, it will bypass the `ansible-windows` installation, and unexpected process can happen. Maybe we need to check if ansible-windows exists after `ansible check`
