### ISSUE TITLE
Remove install of vsphere guestinfo metadata source for cloud-init after v0.21.3

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#675]
**Is your feature request related to a problem? Please describe.**

https://github.com/canonical/cloud-init/pull/953 (thanks @akutz ) adds a new vSphere metadata source into cloud-init, which means we should remove the custom install in image builder at such a time that distro provided cloud-init packages include the new datasource by default. This should be v21.3 (@akutz  will confirm), but with the caveat that the datasource requires netifaces >=0.10.9 but Ubuntu 20.04 is currently 0.10.4, so we will need to review the Ubuntu 20.04 package that actually includes it.

The new datasource is backwards compatible , with key consumers being Cluster API and Cluster API Provider vSphere.

/kind feature

**Comment by codenrhoden** [comment]
/reopen

I think a suitable version was recently published.
