### ISSUE TITLE
DHCP Option 42 doesn't working on Ubuntu 20.04

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#676]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**
Chrony will only have its time source configured via DHCP using dhclient, for which there is a script in /etc/dhcp/dhclient-exit-hooks.d/chrony 

The dhclient script for DHCP on Ubuntu is incompatible with chrony and only supports timesyncd.

Attempting to run dhclient manually gets:

```shell
root@wl-104-md-0-5ccdb4fffd-lv64j:/usr/lib# dhclient
RTNETLINK answers: File exists
Failed to try-restart systemd-timesyncd.service: Unit systemd-timesyncd.service is masked.
```

but chrony does get the time source. Note that the time source gets appended to the default ubuntu list, which might be not ideal.

The issue is that Ubuntu 20.04 uses systemd-networkd, programmed by netplan to configure networking. systemd includes its own DHCP client, which means that the dhclient scripts are no longer used. This would mean that NTP DHCP support would only be supported via systemd-timesyncd and not chrony.

This runs counter us standardising on chrony because we wanted consistent cloud-init support.

There's potentially 2 options:

1. Get chrony working somehow with systemd-networkd.
2. Revert to systemd-timesyncd, but verify cloud-init works

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): Ubuntu 20.04
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by randomvariable** [comment]
@MaxRink , have you seen this one?

**Comment by MaxRink** [comment]
and iirc we should still be able to hook a script to dhcp events in ubuntu 2004

**Comment by randomvariable** [comment]
that script is already there in exit scripts, but the problem is that systemd-networkd doesn't use dhclient.

**Comment by mlichvar** [comment]
There is a networkd-dispatcher [package](https://packages.ubuntu.com/focal-updates/networkd-dispatcher) in Ubuntu to call scripts when the connection status changes with networkd. The chrony package already has a script called by the dispatcher, but it handles just the online/offline state. A new dispatcher script could be added to parse NTP servers from the `networkctl status` output and add them to `chronyd`.

**Comment by SanikaGawhane** [comment]
I am currently looking into this issue. Trying to recreate it to explore possible approaches and solutions.
