### ISSUE TITLE
Should we include provider versions in image versions?

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/image-builder#70]
This is mostly a follow-up issue based on a previous discussion w/ @akutz @codenrhoden @ncdc @detiber @dennisme https://github.com/kubernetes-sigs/image-builder/pull/64#discussion_r329793887 

We recently added CSI support in CAPV which required an update to our machine image because the vSphere CSI driver requires a newer VMX version than what we were using previously. Since machine images are versioned based on Kubernetes versions, we're put in an awkward position for a couple reasons:
* If we update all machine images with the VMX update, we possible break older versions of CAPV pointing at older images that were just updated.
* If only new images get the VMX update, new CAPV versions can't deploy older versions of Kubernetes AND older CAPV versions can't use the newer versions of Kubernetes. 

Ideally if we also versioned images based on the version of the provider, (i.e for CAPV `ubuntu-1804-kube-v1.15.3-capv-v0.5.2`), any Kubernetes version would work on the specified version of CAPV. However, this leaves some open questions:
* if you upgrade CAPV, do you have to upgrade the machine image? For (semantic) minor versions, probably. But probably not required for patch versions? 
* what rules do we follow for updating the machine image on the same Kubernetes version, but a different provider version? Is it any different from updating machine images today?
* what needs to change in our release processes to make this happen? Is it worth the effort?

**Comment by detiber** [comment]
> if you upgrade CAPV, do you have to upgrade the machine image? For (semantic) minor versions, probably. But probably not required for patch versions?

This could greatly complicate the upgrade process...  For CAPA, we specifically released v0.3.9 to use the newer version of image-builder (without custom cloud-init provider) to help avoid needing to do a similar image swap for minor version upgrades.

**Comment by andrewsykim** [comment]
> For CAPA, we specifically released v0.3.9 to use the newer version of image-builder (without custom cloud-init provider) to help avoid needing to do a similar image swap for minor version upgrades.

So for CAPA if I'm on v0.3.9, does that mean I can't use any of the machine images released in older patch versions? Also are all Kubernetes versions re-uploaded using the newer version of the image-builder or just the latest patch versions of Kubernetes?

**Comment by detiber** [comment]
CAPA <= v0.3.8 can use any of the previously released images (that use the images with the kubeadm module), but not any newer released images.

CAPA  v0.3.9 can use both the previously released images and any newly released images.

CAPA v0.4.x can use either the previously released images or any newly released images.

It's not really apples to apples, but ideally we'd have some type of transition path where the tooling can create images that work across a minor version bump.

**Comment by akutz** [comment]
FWIW, this is an odd case in that it's not the contents of the image but some metadata (the HW version) associated with the image. But the long-term issue stands -- what happens when a CVE is found that affects the machine images? We will need to spin updates for all of them. How do we then distribute those? Do we overwrite the older images? Publish new ones? If the latter, how are they versioned?

For example, what if there's a CVE that affects the image builder and it means we have to recreate all our images. Nothing about K8s changed, but we have to rebuild all the images we've already built to address the CVE. With what names do we publish those images?

**Comment by detiber** [comment]
> For example, what if there's a CVE that affects the image builder and it means we have to recreate all our images. Nothing about K8s changed, but we have to rebuild all the images we've already built to address the CVE. With what names do we publish those images?

I would hope that wouldn't require us to modify CAP* providers to consume the new images, so I would expect at least that use case to require re-publishing images with the same name (or in the case of CAPA, the same name prefix with a new timestamp).
