### ISSUE TITLE
Parametrize Windows kubelet Ansible role

### ISSUE THREAD

**Issue by knabben** [kubernetes-sigs/image-builder#702]
**Is your feature request related to a problem? Please describe.**
Not all Kubelet parameters are migrated to Kubelet configuration file (i.e. instance specifics ones), one example is the `--node-ip`, this way there's no way to add an IP to kubelet

**Describe the solution you'd like**
Let windows kubelet pickup the interface can be tricky (https://github.com/kubernetes/kubernetes/issues/104269), forcing the IP via parameter can be an option when building the box (if the IP is static)

**Describe alternatives you've considered**
Rewriting the path of the service after the box is created.
Adding the field in the configuration (not migrated yet).

/kind feature

**Comment by jsturtevant** [comment]
This was mostly designed with capi and kubeadm bootstrapper as the main consumers.  With that in mind it is possible to pass additional flags to kubelet via `/var/lib/kubelet/kubeadm-flags.env` file that kubeadm writes. 

https://github.com/kubernetes-sigs/image-builder/blob/196c549b8f31f890f7839cdd5681c1facd78dad2/images/capi/ansible/windows/roles/kubernetes/templates/StartKubelet.ps1#L16-L17
