### ISSUE TITLE
Azure Windows containerd make targe pass blank pause image

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/image-builder#703]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
run `make build-azure-vhd-windows-2019-containerd`

the ansible output has a blank pause image:

```
Executing Ansible: ansible-playbook -e packer_build_name="vhd-windows-2019-containerd" -e packer_builder_type=azure-arm -e ansible_winrm_server_cert_validation=ignore 
ansible_winrm_operation_timeout_sec=120 ansible_winrm_read_timeout_sec=150 --extra-vars runtime=containerd docker_ee_version=19.03.12 containerd_url=https://github.com/cont
ainerd/containerd/releases/download/v1.5.5/containerd-1.5.5-windows-amd64.tar.gz 
containerd_sha256=036428b8c4055b2eeba7c62ac84dc96552be9a2c14e3a8a6ac4052684cf7
3db0 pause_image= additional_debug_files="" containerd_additional_settings= 
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):windows 2019
- Packer Version: 1.7.4
- Packer Provider: 
- Ansible Version: 2.10.2
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by jsturtevant** [comment]
this looks like it is now working properly in docker either:

```
[1;32m==> vhd-windows-2019: Executing Ansible: ansible-playbook -e packer_build_name="vhd-windows-2019" -e packer_builder_type=azure-arm -e ansible_winrm_server_cert_validation=ignore ansible_winrm_operation_timeout_sec=120 
ansible_winrm_read_timeout_sec=150 --extra-vars runtime=docker-ee 
docker_ee_version=19.03.12 containerd_url=https://github.com/containerd/containerd
/releases/download/v1.5.5/containerd-1.5.5-windows-amd64.tar.gz containerd_sha256=036428b8c4055b2eeba7c62ac84dc96552be9a2c14e3a8a6ac4052684cf7
3db0 pause_image= additional_debug_files="" containerd_additional_settings= 
custom_role_names= http_proxy= https_proxy= no_proxy= 
```

**Comment by perithompson** [comment]
Strange, I haven't seen this happening but perhaps I missed it? I see you have a PR open though so I will give it a try!
