### ISSUE TITLE
Well defined Containerd imports directory

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/image-builder#709]
**Is your feature request related to a problem? Please describe.**

We would like to use the [CAPA AMIs](https://cluster-api-aws.sigs.k8s.io/amis.html) generated by image-builder with some modifications to the Containerd configuration (enabling metrics, adding mirrors). Containerd has an `imports` [config](https://github.com/containerd/containerd/blob/main/docs/man/containerd-config.toml.5.md) that allows users to pass in additional toml config files that will be merged.

See default Containerd configuration:

```
sh-4.2$ containerd config dump
version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
plugin_dir = ""
disabled_plugins = []
required_plugins = []
oom_score = 0
imports = ["/etc/containerd/config.toml"]
...
```
```
sh-4.2$ cat /etc/containerd/config.toml
## template: jinja

# Use config version 2 to enable new configuration fields.
# Config file is parsed as version 1 by default.
version = 2

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "k8s.gcr.io/pause:3.4.1"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
```

**Describe the solution you'd like**

Having a well defined `imports` directory would allow us to drop in configuration overrides at runtime. 

**Describe alternatives you've considered**

- Building our own AMIs
- Using `preKubeadmCommands` in CAPI to modify the Containerd config and add an `imports` field.

All of these work but having a single solution would might be useful for others.

Would love to hear other alternatives!

**Additional context**

/kind feature

**Comment by dlipovetsky** [comment]
For reference, [this is the containerd code](https://github.com/containerd/containerd/blob/c23f52af30b4461dd6ae8224ceb553040e79d4d3/services/server/config/config.go#L288-L314) that resolves the `imports` list entries. Something like `imports = ["/etc/containerd/imports/*.toml"]` would capture all the files matched by the glob.

**Comment by jsturtevant** [comment]
I think this is a cleaner solution to what we have now.  What steps are you preforming for adding the additional containerd toml files to the images?

**Comment by dkoshkin** [comment]
> What steps are you preforming for adding the additional containerd toml files to the images?

We've modified the Containerd config template that always includes an `imports` field, but would like to contribute it back into here.

**Comment by jimmidyson** [comment]
@jsturtevant The additional files imported at runtime into containerd config are added in the standard way via `KubeadmConfigTemplate` `spec.template.spec.files`. This allows, among other things, for e.g. custom credentials to Docker registries (especially important when pulling from Docker Hub due to rate limiting) without baking credentials into the image at build time (which of course would be a Bad Thing).

**Comment by jimmidyson** [comment]
@jsturtevant Yes containerd would require to be restarted unfortunately. This can be handled in prekubeadm commands though iirc.
