### ISSUE TITLE
[cloud-init] Temporarily pin Cloud-Init to v21.1

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#722]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

A bug was introduced in cloud-init that breaks networking under some circumstances #712. We should pin the version until https://github.com/canonical/cloud-init/pull/1058 comes into an update channel

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by akutz** [comment]
Unfortunately the 21.4 release won't have the fix for the latest `set-name` bug, so unless you want to use a package built from `main`, you're stuck with the downgrade. 

* v21.4 will have this fix https://github.com/canonical/cloud-init/pull/1058
* but will not have https://github.com/canonical/cloud-init/pull/1100

**Comment by akutz** [comment]
You know, it's also possible to use 21.4 and simply patch in the fix from https://github.com/canonical/cloud-init/pull/1100...

**Comment by codenrhoden** [comment]
> Unfortunately the 21.4 release won't have the fix for the latest `set-name` bug, so unless you want to use a package built from `main`, you're stuck with the downgrade.
> 
> * v21.4 will have this fix [Fix set-name/interface DNS bug canonical/cloud-init#1058](https://github.com/canonical/cloud-init/pull/1058)
> * but will not have [Fix for set-name bug in networkd renderer canonical/cloud-init#1100](https://github.com/canonical/cloud-init/pull/1100)

The latest is the `networkd` renderer, right? I don't think of it's entirely clear whether we are hitting that or not. I believe Ubuntu is using netplan even though it runs `systemd-networkd`, but perhaps it gets hit on Photon?

**Comment by akutz** [comment]
That is correct, the issue reported by this comment, https://github.com/kubernetes-sigs/image-builder/issues/712#issuecomment-954140935, is when `set-name` is used with the networkd renderer.

**Comment by akutz** [comment]
https://github.com/canonical/cloud-init/pull/1100 was merged.
