### ISSUE TITLE
Windows documentation missing from the capi "book"

### ISSUE THREAD

**Issue by perithompson** [kubernetes-sigs/image-builder#737]
**What steps did you take and what happened:**
Windows documentation in the [book](https://image-builder.sigs.k8s.io/capi/windows/windows.html)  goes to a broken link, it seems the windows.md file has not made it into the "book"

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
/kind bug
/area windows

**Comment by jsturtevant** [comment]
@codenrhoden what are the steps for publishing a new version of the book?

**Comment by CecileRobertMichon** [comment]
/close

fixed in #769
