### ISSUE TITLE
Support running image-builder in RHEL 7

### ISSUE THREAD

**Issue by alexbrand** [kubernetes-sigs/image-builder#78]
The Makefile in images/capi/packer/ami and images/capi/packer/gce uses `shasum` to verify the downloaded packer plugins.

In some distributions, such as RHEL 7, `shasum` is actually `sha256sum`. I think we can update the Makefile to detect whether `shasum` or `sha256sum` is available on the machine. If neither are there, exit with an error.

**Comment by codenrhoden** [comment]
/assign

Yeah, it can definitely be added to user different variants of the same command.

hard part for me is going to be tracking down a RHEL license to test things E2E. I'll start that process. :)

**Comment by codenrhoden** [comment]
An update on this one -- I finally have a working setup that will Kickstart a RHEL 7 image. Took me a while to get a working ISO, a subscription for testing, and a working headless Workstation Pro setup inside my corporate firewall.

Now when I kickstart RHEL, the Ansible scripts fail, so I finally can start tracking this down.
