### ISSUE TITLE
"Unable to read config path" err="path does not exist, ignoring" path="c:\\etc\\kubernetes\\manifests"

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/image-builder#780]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

The images produced for windows are missing a path causing kubelet to output an error. It is non fatal but does add noise to the logs.  

```
E0105 22:28:04.933446    2984 file.go:104] "Unable to read config path" err="path does not exist, ignoring" path="c:\\etc\\kubernetes\\manifests"
```

**What did you expect to happen:**
No error messages because node is configured properly. We should set those paths up properly when configuring kubelet:

https://github.com/kubernetes-sigs/image-builder/blob/d30db3a62b00f1c4598d6cff2920995fe6ee341b/images/capi/ansible/windows/roles/kubernetes/tasks/main.yml#L15

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
/sig windows
/good-first-issue

**Comment by knabben** [comment]
Will take this one..

**Comment by knabben** [comment]
Doing a  `cat C:\var\lib\kubelet\config.yaml`

```
apiVersion: kubelet.config.k8s.io/v1beta1
staticPodPath: c:\etc\kubernetes\manifests
```

shows the default configuration pointing to `c:\etc\kubernetes\manifests`

the default ansible task has a different path creation.
https://github.com/kubernetes-sigs/image-builder/blob/4eea397ee71e0e69209db7c9a9ce8dddab99c898/images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml#L22 

Should we 1) parametrize this parameter 2) fix the `config.yaml` to the correct path.

**Comment by jsturtevant** [comment]
The ansible path creation should be updated to `c:\etc\kubernetes\manifests`. This should be the default (as shown by the kubelet `config.yaml`) and mimic the linux set up.

**Comment by jsturtevant** [comment]
fixed by https://github.com/kubernetes-sigs/image-builder/pull/785
/close
