### ISSUE TITLE
Add support for building CAPI images behind an HTTP proxy

### ISSUE THREAD

**Issue by alexbrand** [kubernetes-sigs/image-builder#79]
As a CAPI user, I want to be able to build my own images behind a corporate HTTP proxy.

At first glance, the following changes are needed:
- Flow http proxy vars into ansible
- Manually download goss 
- Disable the automatic download of goss in the goss plugin

**Comment by codenrhoden** [comment]
A quick update on this after a bit of searching...

Packer already supports the 3 main proxy env vars:

- HTTP_PROXY
- HTTPS_PROXY
- NO_PROXY

So there is nothing to do on the Packer side -- these vars will be honored during any needed ISO downloads.

For Ansible, we'd need to [set the environment](https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html) for the entire playbook. So, we'd need to edit our `playbook.yml` to define the environment, and then pass them in from Packer via `--extra-vars`.
