### ISSUE TITLE
Unable to create centos 7 images in vsphere (python version error)

### ISSUE THREAD

**Issue by ubhide** [kubernetes-sigs/image-builder#794]
**What steps did you take and what happened:**
Executed build using the current latest (v0.1.11) docker image as per the [documented command](https://image-builder.sigs.k8s.io/capi/container-image.html).
`docker run -it --rm --net=host --env PACKER_VAR_FILES=/home/imagebuilder/vsphere.json -v <path of vsphere.json on my machine>:/home/imagebuilder/vsphere.json k8s.gcr.io/scl-image-builder/cluster-node-image-builder-amd64:v0.1.11 build-node-ova-vsphere-centos-7`

Build fails consistently with the following error:
```
 vsphere: TASK [providers : Execute cloud-init-vmware.sh] ********************************
    vsphere: fatal: [default]: FAILED! => {"changed": true, "cmd": "bash -o errexit -o pipefail /tmp/cloud-init-vmware.sh", "delta": "0:00:01.188666", "end": "2022-02-02 19:37:34.788647", "msg": "non-zero return code", "rc": 1, "start": "2022-02-02 19:37:33.599981", "stderr": "Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build
-kv5idA/deepmerge/\nYou are using pip version 8.1.2, however version 22.0.2 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.", "stderr_lines": ["Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-kv5idA/deepmerge/", "You are using pip version 8.1.2, however version 22.0.2 is available."
, "You should consider upgrading via the 'pip install --upgrade pip' command."], "stdout": "using python 2\ninstalling requirements\nCollecting deepmerge>=0.0.5 (from -r /tmp/tmp.5C9RkuSgig (line 1))\n  Downloading https://files.pythonhosted.org/packages/d0/8c/64c915010705420c6a646c5b87d27278d553cec5a0d636d1bcf81d50cbbe/deepmerge-1.0.1.tar.gz\n    Complet
e output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-kv5idA/deepmerge/setup.py'\n    \n    ----------------------------------------", "stdout_lines": ["using python 2", "installing requirements", "Collecting d
eepmerge>=0.0.5 (from -r /tmp/tmp.5C9RkuSgig (line 1))", "  Downloading https://files.pythonhosted.org/packages/d0/8c/64c915010705420c6a646c5b87d27278d553cec5a0d636d1bcf81d50cbbe/deepmerge-1.0.1.tar.gz", "    Complete output from command python setup.py egg_info:", "    Traceback (most recent call last):", "      File \"<string>\", line 1, in <module>", "
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-kv5idA/deepmerge/setup.py'", "    ", "    ----------------------------------------"]}
```

**What did you expect to happen:**
Centos 7 VM template created in vsphere successfully

**Anything else you would like to add:**
Ubuntu images get created successfully, and the centos image also works if the target is Azure (the other option I experimented with), just not with vsphere. 

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi)):

/kind bug
area/provider/vmware

**Comment by codenrhoden** [comment]
Thanks for filing this, @ubhide. I saw the same thing and referenced it here: https://github.com/kubernetes-sigs/image-builder/pull/789#issue-1115315227. I had been meaning to write up an issue for it, but you've done it for me.

Haven't tried to fix it yet, just acknowledging that it's an issue for sure. :)
