### ISSUE TITLE
Security Self Assessment: [STRIDE-TAMPER-2] Produce an SBoM for machine images

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#803]
**Describe the solution you'd like**

As per the Cluster API Security Self Assessment:

Machine images used as Node OS images, can be tampered during build time, during install time and
during runtime

One mitigation:

Create SBoM of the Machine Image and verify checksum as a post build action

**Additional context**
cc @PushkarJ  for more details

/kind feature
/area security

**Comment by randomvariable** [comment]
Please add an area/security label option.

**Comment by PushkarJ** [comment]
/retitle Security Self Assessment: [STRIDE-TAMPER-2] Produce an SBoM for machine images
