### ISSUE TITLE
Switch to cgroups v2 for all images

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/image-builder#819]
The eco system is moving towards cgroups v2 instead of cgroups v1. Kubelet, containerd, runc, cadvisor etc has been updated to work with cgroups v2. Docker Desktop has switched already to cgroups v2 as well by default.

Can we please switch our default images to cgroups v2? thanks!

context: https://github.com/kubernetes/kubernetes/issues/108028

**Comment by codenrhoden** [comment]
Thanks for bringing this up, @dims. Reading through the related issue, seems like changing the default is reasonable, but we definitely want people to still be able to use v1 if they want. Additionally, we'll have to actually check if *all* the OS targets we build are able to use v2.

**Comment by dims** [comment]
@codenrhoden indeed. the title was click-bait-y :) intended to be aspirational for sure!

**Comment by dims** [comment]
@codenrhoden do we want to check if this can be done in 1.25 time frame?

**Comment by dims** [comment]
@t-lo yes, it's going to be .... not easy!
