### ISSUE TITLE
update Ubuntu ISO to newer version to address security update

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/image-builder#83]
please refer to canonical announcement of newer kernel patch, https://news.softpedia.com/news/canonical-outs-new-linux-kernel-security-update-for-ubuntu-18-04-and-16-04-lts-527939.shtml

**Comment by codenrhoden** [comment]
I don't think updating the ISO is required get the newer kernel. The kernel will get upgraded at this step:

https://github.com/kubernetes-sigs/image-builder/blob/24e22ae879eda31d5f68b7a70361e4dc495f0625/images/capi/ansible/roles/common/tasks/debian.yml#L43-L46

When I run `apt-get dist-upgrade` in an Ubuntu VM right now, it tries to install `linux-image-4.15.0-66`, which is the new recommended kernel. So I think we are good here. :)

The latest 18.04 ISO available at http://releases.ubuntu.com/18.04/ hasn't been updated, either.

**Comment by figo** [comment]
Thanks @codenrhoden for looking into it, looks like we can close the issue now.
