### ISSUE TITLE
switch the default image registry in image builder to registry.k8s.io

### ISSUE THREAD

**Issue by neolit123** [kubernetes-sigs/image-builder#845]
this is an item for the k8s 1.25 release cycle.
switch the default image registry in image builder to registry.k8s.io after kubeadm switches to it:
https://github.com/kubernetes/kubeadm/issues/2671

more info:
https://groups.google.com/g/kubernetes-sig-testing/c/U7b_im9vRrM/m/7qywJeUTBQAJ
xref https://github.com/kubernetes-sigs/image-builder/pull/844
xref https://github.com/kubernetes/k8s.io/issues/1834

**Comment by AverageMarcus** [comment]
I just hit this issue today trying to build the new v1.25.0 build. It's trying to pull coredns:v1.9.3 from the old registry which doesn't exist.

**Comment by neolit123** [comment]
likely related to https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images
and it depends on the kubeadm version. 1.25 will threat registry.k8s.io as the default and the coredns path differs between default and non default registry.
