### ISSUE TITLE
Cut an image-builder release tag that supports the latest windows fixes

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/image-builder#866]
**Is your feature request related to a problem? Please describe.**
Recent fix to  https://github.com/kubernetes-sigs/image-builder/issues/815 is required to do airgapped windows image-builder in a manner that is idiomatic to CAPV clusters.

**Describe the solution you'd like**

We'd like to cut an image-builder patch release that has this fix

```
probably an 0.1.12 is good enough since this is only a patch to a bug , no new major features

```

/kind feature

**Comment by jayunit100** [comment]
steps TODO for anyone wanting to create this tag : 
- diff the master branch commits from what is in 0.11.1
- find any bugfixes that we want to put into 0.11.2
- add those tickets to this ticket
- go to the image-builder mailing list and ask folks to cut this release - and also ask in the image-builder slack channel

**Comment by codenrhoden** [comment]
Once #869 and #868 get merged, I think we're in a good place to tag.
