### ISSUE TITLE
qemu,raw: Ubuntu 20.04 EFI builds are broken

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/image-builder#885]
**What steps did you take and what happened:**

```
PACKER_LOG=1 make build-qemu-ubuntu-2004-efi
```

The build fails with the following error:

```
2022/05/11 13:21:06 packer-builder-qemu plugin: Qemu stderr: qemu-system-x86_64: -drive file=OVMF.fd,if=pflash,format=raw,readonly=on: Could not open 'OVMF.fd': No such file or directory
==> qemu: Error launching VM: Qemu failed to start. Please run with PACKER_LOG=1 to get more info.
```

~The same is theoretically true for `make build-raw-ubuntu-2004-efi`, however raw builds are currently broken due to https://github.com/kubernetes-sigs/image-builder/issues/879.~
**Update:** The issue reproduces for raw builds, too.

**What did you expect to happen:**
I expected the build to work.

**Anything else you would like to add:**
[Looks](https://wiki.ubuntu.com/UEFI/OVMF) like `OVMF.fd` should be a firmware file used to emulate EFI in VMs. Ideally we should create (or download) this file automatically upon build. If we can't do that, we should document that it's required and probably exempt the EFI builds from `make build-{qemu|raw}-all`.

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)): image-builder

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): Ubuntu 20.04 LTS
- Packer Version: v1.8.0
- Packer Provider: qemu
- Ansible Version: irrelevant
- Cluster-api version (if using): irrelevant
- Kubernetes version: (use `kubectl version`): irrelevant

/kind bug
 
cc @MaxRink

**Comment by AverageMarcus** [comment]
From my (limited) understanding, this requires some qemu(-kvm) tooling to be installed onto the machine you're running this on. 
We managed to get around this at Giant Swarm by using the docker image running the following:
```
apt-get update && apt-get install -y qemu qemu-kvm
```

Maybe it makes sense to have this built in to the standard image-builder container image to at least make sure that is useable out-of-the-box with qemu. 

I'm not sure how best to handle this when running `make` directly other than stating it as a pre-requisite. Do you have any ideas?

**Comment by AverageMarcus** [comment]
Actually, looks like this is now added to the Docker image: https://github.com/kubernetes-sigs/image-builder/commit/6b2a0ecdf8a73e56c143a626b4630fb060e85473

**Comment by mboersma** [comment]
@johananl is this still an issue now that #879 is closed? (See also #1122.)

**Comment by johananl** [comment]
The `OVMF.fd` error still reproduces for me @mboersma. IIUC #879 didn't affect this issue but rather the ability to **try** to reproduce this issue for raw builds (because you need to be able to run a raw build in order to determine if the EFI raw build is broken).

Thanks for the info @AverageMarcus. AFAICT you're talking about the QEMU/KVM dependency which is off course necessary, however I'm not sure how satisfying this dependency fixes the problem with the missing `OVMF.fd` file.

**Comment by johananl** [comment]
This seems very relevant: https://github.com/tianocore/tianocore.github.io/wiki/How-to-run-OVMF

**Comment by johananl** [comment]
I've reproduced the problem using the Docker-based build, too:

```
docker run -it --rm --net=host -e PACKER_LOG=1 registry.k8s.io/scl-image-builder/cluster-node-image-builder-amd64:v0.1.17 build-qemu-ubuntu-2004-efi
```

**Comment by johananl** [comment]
I'll try to build and use OVMF using the instructions [above](https://github.com/kubernetes-sigs/image-builder/issues/885#issuecomment-1677150919) and report here.
