### ISSUE TITLE
Host bootstrap Ignition files in image-builder repo

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/image-builder#890]
Flatcar Container Linux uses Ignition (instead of e.g. Kickstart) as a bootstrap config format. On some platforms (e.g. QEMU, OVA) it's necessary to provide Ignition config during the image build process.

Right now we're consuming these files from https://github.com/flatcar-linux/flatcar-packer-qemu. Example:

https://github.com/kubernetes-sigs/image-builder/blob/60128fff6ce397998e58c491ac593473372c700b/images/capi/packer/qemu/qemu-flatcar.json#L3

This is far from ideal for multiple reasons, the main one being that the stability of the image-builder Flatcar builds is now dependent on an external repository which currently doesn't use proper versioning, releases etc.

In https://github.com/kubernetes-sigs/image-builder/pull/873#discussion_r866007976 we're discussing the matter. There are multiple ways to address the issue:

1. Get rid of the need to pass Ignition config at build time altogether. This would be best as it gets rid of the problem but is likely not feasible because we might need Ignition in some cases (for example to ensure we disable automatic updates at build time).
1. Find a provider-native way (e.g. AWS user data) to pass Ignition data for _all_ providers.
1. Use `curl` with an internet URL as part of the build process and host the Ignition files inside the image-builder repo.

I suggest we start by hosting the Ignition files in the image-builder repo, just like we're already doing with Kickstart used by other distros. In future iterations we may be able to switch to a provider-native way to inject Ignition data to builder VMs or even get rid of the need for bootstrap Ignition config altogether, however at least for now we'll have something stable that works.

/assign

**Comment by jsturtevant** [comment]
Hosting the files in the repo seems to make most sense for now. I don't have a ton of context on the how/why you would remove ignition or provide a native way to pass ignition.  I would follow your lead on that, but for now we can iterate with the files in the reposiotory.
