### ISSUE TITLE
qemu,raw: Race between Flatcar installation and Packer

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/image-builder#892]
**What steps did you take and what happened:**

Flatcar ships with sshd enabled by default. Installing Flatcar entails booting into Flatcar from an ISO and running the installation command (`flatcar-install`). Unlike other distros (e.g. Ubuntu), the Flatcar installation is done from a live instance of Flatcar, which means SSH is enabled on the temporary Flatcar instance from which the installation script is executed.

Packer treats the availability of the SSH port as an indication that the OS installation is done. To prevent Packer from attempting to run Ansible before Flatcar is installed to disk, a static wait time is currently appended to the Flatcar boot command, which means there is a potential race between the installation script and Packer in the worst case and an unnecessary increase of the build time in the best case. The above leads to occasional Packer errors in Flatcar builds, especially when the Flatcar installation process is slow due to network bandwidth limitations.

To reproduce, run a Flatcar build with the `install_wait` variable set to one second to simulate a case where the Flatcar installation didn't manage to complete before Packer attempted to start the Ansible provisioning process:

```
cat <<EOF >flatcar.json
{
  "install_wait": "1s"
}
EOF

PACKER_VAR_FILES=flatcar.json FLATCAR_VERSION=3139.2.1 make build-qemu-flatcar
```

Output:

```
...
==> qemu: Waiting for SSH to become available...
==> qemu: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password keyboard-interactive], no supported methods remain
==> qemu: Deleting output directory...
Build 'qemu' errored after 4 minutes 43 seconds: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password keyboard-interactive], no supported methods remain
```

We get an SSH auth error because we're attempting to SSH into the **temporary** Flatcar instance with the `builder` user which is available only once Flatcar boots from disk.

**What did you expect to happen:**
I expected the `ssh_timeout` parameter to take effect, namely the build should succeed as long as it doesn't take more than 2 hours.

I am working on a PR to address this.

**Anything else you would like to add:**
None

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
/assign

**Comment by codenrhoden** [comment]
Thank you for explaining this so well. Now I understand your changes in #893.
