### ISSUE TITLE
CAPV images for Ubuntu have unattended upgrades enabled

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#90]
This must happen by default with Ubuntu, but he current images have the `unattended-upgrades` package installed and enabled. Furthermore, there are systemd units that are trying to do a daily apt-get update... These units are:

- `apt-daily.{service,timer}`
- `apt-daily-upgrade.{service,timer}`

Since the images are supposed by immutable, we *really* don't want any packages changing automatically, and we don't need any daily tasks to fetch new package lists. This should all be cleaned up.

/assign

**Comment by codenrhoden** [comment]
Just to follow-up on this one, I want to pose the question: Are the images created by this tool intended to be immutable?

I believe the answer to this question is yes -- if any package update is required, the intent is to build a new image.

Other uses may not agree with this process. I know from my perspective, I have internal requirements for these images to be immutable, so at a minimum I need the _option_ to disable these services. The question then becomes -- should it be immutable by default?

/cc @akutz @detiber @figo

**Comment by detiber** [comment]
@codenrhoden based on the use cases for the tool that we've described so far, I think the best option is to default to immutable. If someone wants to have mutable behavior, we shouldn't necessarily stop them, but it should definitely be the exception.

**Comment by codenrhoden** [comment]
> @codenrhoden based on the use cases for the tool that we've described so far, I think the best option is to default to immutable. If someone wants to have mutable behavior, we shouldn't necessarily stop them, but it should definitely be the exception.

This is my intended approach, I just wanted to get buy-in before I do it. I'll bring it up in today's community meeting as well. I know you won't be there, so thanks for sharing your input here.

**Comment by randomvariable** [comment]
FWIW, did consider adding the following, to lock the Kubernetes version but allow package updates to the rest of the system, just in case someone does do it, it shouldn't break the node.

https://github.com/randomvariable/wardroom/blob/fedora-modernization/ansible/roles/kubernetes/tasks/debian.yml#L45-L65

**Comment by akutz** [comment]
So CAPV is hitting flakes all the time now because of the boot-time apt tasks. FWIW, this [is a known issue in Ubuntu](https://askubuntu.com/questions/1038923/do-i-really-need-apt-daily-service-and-apt-daily-upgrade-service), and apparently it's by mistake as these tasks [should be run post-boot](https://askubuntu.com/questions/800479/ubuntu-16-04-slow-boot-apt-daily-service).

From CAPV's perspective this is a P1 as it's causing our e2e jobs to flake 2-3/5 times.

cc @yastij

**Comment by codenrhoden** [comment]
@akutz Thanks for letting me know. I'll get a fix in for it in the next couple of days!
