### ISSUE TITLE
How can we build RHEL 8 OVAs

### ISSUE THREAD

**Issue by anoopl** [kubernetes-sigs/image-builder#903]
**Is your feature request related to a problem? Please describe.**
We are not able to find the command for building RHEL 8 OVAs
**Describe the solution you'd like**

We wanted to build a custom OVA using RHEL 8 ISO. We could not find the build command for RHEL 8
**Describe alternatives you've considered**

Can we use commands for RHEL 7 or Rocky Linux * build OVA commands for this, I am not sure about that

/kind feature

**Comment by davidjumani** [comment]
It's currently not added to the ova provider, but as a workaround, It can be built via qemu `build-qemu-rhel-8` and then converted to an ova by running `./hack/convert-cloudstack-image.sh ./output/<build-name>/<build-name> v
`

**Comment by anoopl** [comment]
@davidjumani  Thank you so much for the reply!
I already created the code for building RHEL-8 and able to build the image successfully
Only tested or created code for Vsphere OVA Build
Tested this with TKG specs
I am wondering how can I write/generate Goss specs for the testing
It will be great if you can share some guide lines for sending a PR

**Comment by davidjumani** [comment]
@anoopl Looks like there's already a PR for the same at https://github.com/kubernetes-sigs/image-builder/pull/870
Perhaps you can contribute to it :)

**Comment by anoopl** [comment]
@davidjumani I saw that PR unfortunately when I was looking at PR test cases
It looks like it covers AMIs as well just not OVA
Will it be accepted if I send a separate PR

**Comment by kkeshavamurthy** [comment]
@anoopl Seems like #870 has not had any updates in close to 3months. Feel free to open up your PR and we'll be happy to review it.

**Comment by kkeshavamurthy** [comment]
Fixed in https://github.com/kubernetes-sigs/image-builder/pull/943

/close
