### ISSUE TITLE
Fix etcd-network-tuning.sh location for Flatcar

### ISSUE THREAD

**Issue by kopiczko** [kubernetes-sigs/image-builder#906]
**What steps did you take and what happened:**

After merging https://github.com/kubernetes-sigs/image-builder/pull/901 flatcar build fails because of read-only `/usr/local/bin`:

```
    qemu: TASK [node : Copy etcd network tuning script] **********************************
    qemu: fatal: [default]: FAILED! => {"changed": false, "checksum": "9b8498c353396b5550fde1af334e0f4030c7b7bd", "msg": "Destination /usr/local/bin not writable"}
```

**What did you expect to happen:**

Build passing.

**Anything else you would like to add:**

N/A

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): macOS 12.4
- Packer Version: 1.8.0
- Packer Provider:
- Ansible Version: 2.12.5
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
CC @invidian

**Comment by invidian** [comment]
I think `/opt/bin` could be used as an alternative for Flatcar.

**Comment by invidian** [comment]
FYI opened #923 as an alternative to #907, which addresses only this issue, so should be easier to merge. It also uses `/opt/bin` only for Flatcar.
