### ISSUE TITLE
Template error while templating string: no filter named 'search'.

### ISSUE THREAD

**Issue by prankul88** [kubernetes-sigs/image-builder#92]
My aim is build capi ova image on my linux system.
On running `make build-ova-ubuntu1804`, I am getting an error `Build 'ubuntu-1804' errored: Error executing Ansible: Non-zero exit status: exit status 2`

On inspecting the provisioning steps, there seems to be an error with file images/capi/ansible/roles/providers/tasks/main.yml

**OUTPUT**

Last few lines of output were like this.

> ubuntu-1804: TASK [kubernetes : Install kubelet service] ************************************
    ubuntu-1804: skipping: [default]
    ubuntu-1804:
    ubuntu-1804: TASK [kubernetes : Ensure that the kubelet is running] *************************
    ubuntu-1804: ok: [default]
    ubuntu-1804:
    ubuntu-1804: TASK [kubernetes : Create the Kubernetes version file] *************************
    ubuntu-1804: changed: [default]
    ubuntu-1804:
    ubuntu-1804: TASK [kubernetes : Create kubeadm config file] *********************************
    ubuntu-1804: changed: [default]
    ubuntu-1804:
    ubuntu-1804: TASK [kubernetes : Kubeadm pull images] ****************************************
    ubuntu-1804: changed: [default]
    ubuntu-1804:
    ubuntu-1804: TASK [kubernetes : delete kubeadm config] **************************************
    ubuntu-1804: changed: [default]
    ubuntu-1804:
    ubuntu-1804: TASK [providers : include_tasks] ***********************************************
    ubuntu-1804: skipping: [default]
    ubuntu-1804:
    ubuntu-1804: TASK [providers : include_tasks] ***********************************************
    ubuntu-1804: fatal: [default]: FAILED! => {"msg": "The conditional check 'packer_builder_type | search('vmware')' failed. **The error was: template error while templating string: no filter named 'search'. String: {% if packer_builder_type | search('vmware')** %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/necuser/go/src/sigs.k8s.io/image-builder/images/capi/ansible/roles/providers/tasks/main.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_tasks: vmware.yml\n  ^ here\n"}
    ubuntu-1804:
    ubuntu-1804: PLAY RECAP *********************************************************************
    ubuntu-1804: default                    : ok=25   changed=18   unreachable=0    failed=1    skipped=36   rescued=0    ignored=0
    ubuntu-1804:
==> ubuntu-1804: Provisioning step had errors: Running the cleanup provisioner, if present...
==> ubuntu-1804: Stopping virtual machine...
==> ubuntu-1804: Deleting output directory...
Build 'ubuntu-1804' errored: Error executing Ansible: Non-zero exit status: exit status 2
==> Some builds didn't complete successfully and had errors:
--> ubuntu-1804: Error executing Ansible: Non-zero exit status: exit status 2
==> Builds finished but no artifacts were created.
Makefile:44: recipe for target 'build-ova-ubuntu-1804' failed
make: *** [build-ova-ubuntu-1804] Error 1

**Comment by moondev** [comment]
I have also observed this error when using the newest Ansible release `2.9.x`. Ansible `2.8.5` works with no issues for me.

**Comment by prankul88** [comment]
@moondev Thanks, I will try that version.

**Comment by prankul88** [comment]
> I have also observed this error when using the newest Ansible release `2.9.x`. Ansible `2.8.5` works with no issues for me.

@moondev Yes it is working as exptected with 2.8.5 . Not sure why this is happening

**Comment by prankul88** [comment]
Probably best to close this issue as it is more version related.

**Comment by geira** [comment]
Filters have changed in 2.9 (you should have gotten plenty of deprecation warnings when running under 2.8). Try changing to `if packer_builder_type is search('vmware')` in roles/providers/tasks/main.yml.
