### ISSUE TITLE
Formalize process for rev'ing versions included in images

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#94]
In the last community meeting, the topic was brought up of how and when we bump verions of things included in the image. Namely, things like `containerd` and `cni`. We should formalize how and when these packages can be bumped up, rather than just being at the whim of someone opening a PR.

**Comment by detiber** [comment]
As part of this we should probably formalize a process for routinely checking/validating that the versions we are currently deploying do not have any known security related issues
