### ISSUE TITLE
Should default images include NFS utilities

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/image-builder#95]
The current images install support for making NFS mounts. As brought up in #64, this does leave open ports that some users may find undesirable. Rather than explicitly disabling those ports, should it instead be left to a user to customize their image by adding NFS support if they want it?

**Comment by detiber** [comment]
I'm okay with removing NFS support by default.

**Comment by ncdc** [comment]
This has been open for a while - have we made any progress on a resolution?

**Comment by codenrhoden** [comment]
yeah, I should pick this up again. Given the very little feedback received, I'll remove NFS by default. users can add it back if they like. That will also resolve the rpcbind issue (#64).

/assign
