### ISSUE TITLE
images/capi/ova-ubuntu: cloud-init does not work in OpenStack

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/image-builder#96]
Hi,

I'm using the CAPI Ubuntu image in OpenStack. My problem is that cloud-init doesn't detect OpenStack correctly (My assumption is the ova image is meant to be also used in OpenStack).

I'm building and deploying the image like this:

```bash
cd images/capi
make build-ova-ubuntu-1804

qemu-img convert -f vmdk -O qcow2 -c ./output/ubuntu-1804-kube-v1.16.2/ubuntu-1804.ova.vmdk ./output/ubuntu-1804-kube-v1.16.2/ubuntu-1804.ova.qcow2

openstack image create --disk-format qcow2 \                                                                                                       
  --private \            
  --container-format bare \
  --file ./output/ubuntu-1804-kube-v1.16.2/ubuntu-1804.ova.qcow2 ubuntu-1804-kube-v1.16.2
```

Then I'm just using Cluster API OpenStack to create a cluster.

I would expect that cloud-init detects OpenStack as datasource and retrieves the metadata. Instead it only trys to detect the vmware-guestinfo datasource. 

![2019-11-10_10-47-43](https://user-images.githubusercontent.com/4662360/68542023-94420d80-03a7-11ea-8360-c6467885eeee.png)

A simple fix is just not installing the vmware-guestinfo datasource: https://github.com/sbueringer/image-builder/pull/2/files

I'm not sure for what the ova image is meant to be used (local development?). But the way it's currently implemented seems to make it impossible to use on OpenStack because the datasources are overwritten in the vmware-guestinfo install script:
* https://github.com/vmware/cloud-init-vmware-guestinfo/blob/master/install.sh#L105
* https://github.com/vmware/cloud-init-vmware-guestinfo/blob/master/99-DataSourceVMwareGuestInfo.cfg#L13

**Comment by figo** [comment]
cc @akutz @codenrhoden

**Comment by akutz** [comment]
Hi @sbueringer,

The OVA was not meant for use with OpenStack, but I think it shouldn't be overly difficult to make it work with both vSphere and OpenStack. 

We just need to update [this](https://github.com/vmware/cloud-init-vmware-guestinfo/blob/master/99-DataSourceVMwareGuestInfo.cfg#L13) file to include the datasource you want, or perhaps even just have the file include all the defaults with the addition of the guest info datasource. Thoughts?

**Comment by sbueringer** [comment]
Sounds good to me. The only problem seems to be that the installation of the vmware guest datasource excludes all other datasources via this config file. I'll prepare a PR to add a new file with the default datasources + `VMwareGuestInfo` and remove the `99-DataSourceVMwareGuestInfo.cfg`.

**Comment by akutz** [comment]
Hi @sbueringer,

By the way, I think @figo may have been the one that organized the builders as they are now, with the `ova` directory. Do I remember that correctly @figo? The reason I highlight that is because the sensible roles actually relate explicitly to `vmware` or `vsphere`, not `ova`. 

So while it may be possible to make the current OVA work with OpenStack, I'd rather do one of the following:

1. Rename the `ova` directory to `vsphere-ova`
2. Create a separate `openstack-ova` directory

**or**

1. Rename the ansible roles currently specific to `vmware` to something that aligns instead with `ova`
2. Update the roles/datasource so the OVA is compatible with both vSphere and OpenStack

**Comment by akutz** [comment]
> Sounds good to me. The only problem seems to be that the installation of the vmware guest datasource excludes all other datasources via this config file. I'll prepare a PR to add a new file with the default datasources + `VMwareGuestInfo` and remove the `99-DataSourceVMwareGuestInfo.cfg`.

Hi @sbueringer,

I'd rather you didn't. This is a bigger issue IMO, and I'd like to fix it at the root in the guest info repo - https://github.com/vmware/cloud-init-vmware-guestinfo. Can you possible make the change there? Either way we have to rebuild the OVA, so it doesn't really matter to that where the change is, but I'd like it to be in the place that creates the widest solution. Thoughts?

**Comment by sbueringer** [comment]
> > Sounds good to me. The only problem seems to be that the installation of the vmware guest datasource excludes all other datasources via this config file. I'll prepare a PR to add a new file with the default datasources + `VMwareGuestInfo` and remove the `99-DataSourceVMwareGuestInfo.cfg`.
> 
> Hi @sbueringer,
> 
> I'd rather you didn't. This is a bigger issue IMO, and I'd like to fix it at the root in the guest info repo - https://github.com/vmware/cloud-init-vmware-guestinfo. Can you possible make the change there? Either way we have to rebuild the OVA, so it doesn't really matter to that where the change is, but I'd like it to be in the place that creates the widest solution. Thoughts?

Yup, sounds good to me.

**Comment by sbueringer** [comment]
> Hi @sbueringer,
> 
> By the way, I think @figo may have been the one that organized the builders as they are now, with the `ova` directory. Do I remember that correctly @figo? The reason I highlight that is because the Ansible roles actually relate explicitly to `vmware` or `vsphere`, not `ova`.
> 
> So while it may be possible to make the current OVA work with OpenStack, I'd rather do one of the following:
> 
> 1. Rename the `ova` directory to `vsphere-ova`
> 2. Create a separate `openstack-ova` directory
> 
> **or**
> 
> 1. Rename the ansible roles currently specific to `vmware` to something that aligns instead with `ova`
> 2. Update the roles/datasource so the OVA is compatible with both vSphere and OpenStack

We took a look today at different options how we're building our images in the future and it looks like we're probably migrating to qemu/kvm anyway. Because we're using multiple different OpenStacks internally (VMWare Integrated OpenStack and kvm based OpenStacks) we need `.qcow2` and `.vmdk` images. Right now we're building `.vmdk` images and converting them to `.qcow2`. But I think in the future we would be building `.qcow2` and just convert them to `.vmdk`.

So the solution for my problem would probably be to add another folder parallel to ova called `qemu`.

For everybody else it might be a good option to make the datasources configurable via some Packer variables? So that it's maybe `VMwareGuestInfo` per default but could easily overwritten with e.g. `VMwareGuestInfo, OpenStack`.

**Comment by akutz** [comment]
Hi @sbueringer,

> We took a look today at different options how we're building our images in the future and it looks like we're probably migrating to qemu/kvm anyway. Because we're using multiple different OpenStacks internally (VMWare Integrated OpenStack and kvm based OpenStacks) we need both .qcow2 and .vmdk images. Right now we're building .vmdk images and converting them to .qcow2. But I think in the future we would be building .qcow2 and just convert them to .vmdk.

I don't think this is necessarily a separate requirement. I originally thought to create `qcow` or `raw` files and then convert them to `vmdk`. Truthfully an OVA is just a `tar` with a special file layout. You can inflate it to recover the `vmdk` inside and convert it. Or you can convert the `vmdk` in a post-build script.

> For everybody else it might be a good option to make the datasources configurable via some Packer variables? So that it's maybe `VMwareGuestInfo` per default but could easily overwritten with e.g. `VMwareGuestInfo`, `OpenStack`.

I agree that is a good option. I'll work on a PR for that.

**Comment by sbueringer** [comment]
> Hi @sbueringer,
> 
> > We took a look today at different options how we're building our images in the future and it looks like we're probably migrating to qemu/kvm anyway. Because we're using multiple different OpenStacks internally (VMWare Integrated OpenStack and kvm based OpenStacks) we need both .qcow2 and .vmdk images. Right now we're building .vmdk images and converting them to .qcow2. But I think in the future we would be building .qcow2 and just convert them to .vmdk.
> 
> I don't think this is necessarily a separate requirement. I originally thought to create `qcow` or `raw` files and then convert them to `vmdk`. Truthfully an OVA is just a `tar` with a special file layout. You can inflate it to recover the `vmdk` inside and convert it. Or you can convert the `vmdk` in a post-build script.
> 

Okay perfect. We'll work on a qemu/kvm build (based on image-builder) internally anyway during the next few weeks. I personally are not available for much longer this year. But then I think we can compare solutions and think about how/if we can merge them.

> > For everybody else it might be a good option to make the datasources configurable via some Packer variables? So that it's maybe `VMwareGuestInfo` per default but could easily overwritten with e.g. `VMwareGuestInfo`, `OpenStack`.
> 
> I agree that is a good option. I'll work on a PR for that.

Thx :)

**Comment by sbueringer** [comment]
Just fyi. We have some OpenStack specific changes here: https://github.com/c445/image-builder/

We also have a kvm based bild with the packer qemu builder. I'll try to upstream this early next year if it makes sense.

**Comment by moshloop** [comment]
I would recommend also looking at the konfigadm based builder, as it uses kvm/qemu directly

**Comment by sbueringer** [comment]
@akutz I (or one of my colleagues) would open a PR for a qemu-based build for the capi images. The build looks more or less like this commit here: https://github.com/sbueringer/image-builder/commit/c5effcdb4d100d9e109c307d5ad20e1eaabf5b19

**Comment by hidekazuna** [comment]
@akutz @sbueringer I already proposed PR #169 which is tested on OpenStack Stein. Please review the PR.

**Comment by sbueringer** [comment]
@hidekazuna Ah cool. I wasn't aware of this PR. Looks very similar
