### ISSUE TITLE
Provide Ubuntu 22.04 support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/image-builder#960]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Currently we only supports Provide Ubuntu 20.04

**Describe alternatives you've considered**

**Additional context**

/kind feature

**Comment by joekr** [comment]
Sorry about that @andyzhangx I didn't mean to close the issue I should have used Ref instead of Fix in my PR.

**Comment by dtzar** [comment]
@andyzhangx - this appears to be resolved by #1006

**Comment by joekr** [comment]
@sriramandev should your PR have closed this issue? or simply referred to it. See the above comment were I accidentally closed this larger issue with my PR.
